import json

with open('/workspace/src/data/lenses.json', 'r', encoding='utf-8') as f:
    lenses = json.load(f)

additional_lenses = [
    # 更多胶片时代镜头
    {
        'id': 'canon-ef-35-2-usm',
        'brand': 'Canon', 'mount': 'EF', 'model': 'Canon EF 35mm f/2 USM',
        'modelCode': 'EF35/2 USM', 'nickname': '人文经典', 'era': 'film', 'year': 1990,
        'type': 'prime', 'focalLength': '35mm', 'aperture': 'f/2', 'isStabilized': False,
        'weight': 335, 'minFocusDistance': '0.3m', 'filterSize': '58mm',
        'priceNew': 3499, 'priceUsedMin': 800, 'priceUsedMax': 1500, 'retentionRate': 48, 'ownershipCount': 'high',
        'pros': ['轻便', '对焦快', '人文焦段', '价格适中'],
        'cons': ['无防抖', '光圈一般'],
        'commonIssues': ['对焦环松动'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+35mm+f2+USM+lens+classic+prime&image_size=square',
        'purchaseAdvice': '人文摄影入门首选',
        'specs': {'镜片组': '7片6组', '光圈叶片': '8片', '放大倍率': '0.15倍'}
    },
    {
        'id': 'canon-ef-28-28-usm',
        'brand': 'Canon', 'mount': 'EF', 'model': 'Canon EF 28mm f/2.8 USM',
        'modelCode': 'EF28/2.8 USM', 'nickname': '广角入门', 'era': 'film', 'year': 1992,
        'type': 'prime', 'focalLength': '28mm', 'aperture': 'f/2.8', 'isStabilized': False,
        'weight': 225, 'minFocusDistance': '0.25m', 'filterSize': '52mm',
        'priceNew': 2499, 'priceUsedMin': 500, 'priceUsedMax': 1000, 'retentionRate': 35, 'ownershipCount': 'medium',
        'pros': ['超轻便', '价格便宜', '广角焦段'],
        'cons': ['无防抖', '光圈较小'],
        'commonIssues': ['对焦马达老化'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+28mm+f2.8+USM+lens+wide+angle+prime+vintage&image_size=square',
        'purchaseAdvice': '广角入门选择',
        'specs': {'镜片组': '6片5组', '光圈叶片': '5片', '放大倍率': '0.15倍'}
    },
    {
        'id': 'canon-ef-100-28-usm',
        'brand': 'Canon', 'mount': 'EF', 'model': 'Canon EF 100mm f/2.8 USM',
        'modelCode': 'EF100/2.8 USM', 'nickname': '人像经典', 'era': 'film', 'year': 1991,
        'type': 'prime', 'focalLength': '100mm', 'aperture': 'f/2.8', 'isStabilized': False,
        'weight': 525, 'minFocusDistance': '0.9m', 'filterSize': '58mm',
        'priceNew': 3999, 'priceUsedMin': 800, 'priceUsedMax': 1500, 'retentionRate': 42, 'ownershipCount': 'high',
        'pros': ['人像焦段', '成像锐利', '价格适中'],
        'cons': ['无防抖', '重量较大'],
        'commonIssues': ['对焦环卡顿'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+100mm+f2.8+USM+lens+portrait+prime+vintage&image_size=square',
        'purchaseAdvice': '人像入门首选',
        'specs': {'镜片组': '8片7组', '光圈叶片': '8片(圆形)', '放大倍率': '0.12倍'}
    },
    {
        'id': 'canon-ef-135-2-usm',
        'brand': 'Canon', 'mount': 'EF', 'model': 'Canon EF 135mm f/2 USM',
        'modelCode': 'EF135/2 USM', 'nickname': '空气切割机', 'era': 'film', 'year': 1994,
        'type': 'prime', 'focalLength': '135mm', 'aperture': 'f/2', 'isStabilized': False,
        'weight': 565, 'minFocusDistance': '0.9m', 'filterSize': '72mm',
        'priceNew': 7999, 'priceUsedMin': 2500, 'priceUsedMax': 4000, 'retentionRate': 68, 'ownershipCount': 'medium',
        'pros': ['大光圈', '焦外柔美', '成像锐利', '经典人像'],
        'cons': ['无防抖', '价格较高'],
        'commonIssues': ['对焦马达异响'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+135mm+f2+USM+lens+portrait+prime+classic&image_size=square',
        'purchaseAdvice': '人像摄影经典',
        'specs': {'镜片组': '8片6组', '光圈叶片': '8片(圆形)', '放大倍率': '0.12倍'}
    },
    {
        'id': 'canon-ef-300-4l-usm',
        'brand': 'Canon', 'mount': 'EF', 'model': 'Canon EF 300mm f/4L USM',
        'modelCode': 'EF300/4L USM', 'nickname': '小绿', 'era': 'film', 'year': 1994,
        'type': 'prime', 'focalLength': '300mm', 'aperture': 'f/4', 'isStabilized': False,
        'weight': 1190, 'minFocusDistance': '1.5m', 'filterSize': '77mm',
        'priceNew': 12999, 'priceUsedMin': 3000, 'priceUsedMax': 5000, 'retentionRate': 55, 'ownershipCount': 'medium',
        'pros': ['长焦定焦', 'L头品质', '相对轻便'],
        'cons': ['无防抖', '价格较高'],
        'commonIssues': ['脚架环松动'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+300mm+f4L+USM+lens+telephoto+prime+green+ring&image_size=square',
        'purchaseAdvice': '长焦入门首选',
        'specs': {'镜片组': '10片8组', '光圈叶片': '8片(圆形)', '放大倍率': '0.18倍'}
    },
    # 更多数码时代镜头
    {
        'id': 'canon-ef-24-70-28-l-usm',
        'brand': 'Canon', 'mount': 'EF', 'model': 'Canon EF 24-70mm f/2.8L USM',
        'modelCode': 'EF24-70/2.8L USM', 'nickname': '镜皇一代', 'era': 'digital', 'year': 2002,
        'type': 'zoom', 'focalLength': '24-70mm', 'aperture': 'f/2.8', 'isStabilized': False,
        'weight': 950, 'minFocusDistance': '0.38m', 'filterSize': '77mm',
        'priceNew': 10999, 'priceUsedMin': 3000, 'priceUsedMax': 5000, 'retentionRate': 48, 'ownershipCount': 'high',
        'pros': ['恒定f/2.8', 'L头品质', '成像优秀'],
        'cons': ['无防抖', '重量大'],
        'commonIssues': ['镜筒松动', '对焦环卡顿'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+24-70mm+f2.8L+USM+lens+standard+zoom+professional&image_size=square',
        'purchaseAdvice': '专业标变首选',
        'specs': {'镜片组': '13片10组', '光圈叶片': '8片(圆形)', '放大倍率': '0.29倍'}
    },
    {
        'id': 'canon-ef-70-200-4l-is-usm',
        'brand': 'Canon', 'mount': 'EF', 'model': 'Canon EF 70-200mm f/4L IS USM',
        'modelCode': 'EF70-200/4L IS USM', 'nickname': '爱死小小白', 'era': 'digital', 'year': 2006,
        'type': 'zoom', 'focalLength': '70-200mm', 'aperture': 'f/4', 'isStabilized': True,
        'weight': 760, 'minFocusDistance': '1.2m', 'filterSize': '67mm',
        'priceNew': 8999, 'priceUsedMin': 4000, 'priceUsedMax': 6000, 'retentionRate': 72, 'ownershipCount': 'high',
        'pros': ['轻便', '带防抖', '成像优秀', '价格适中'],
        'cons': ['光圈较小'],
        'commonIssues': ['防抖机构异响'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+70-200mm+f4L+IS+lens+telephoto+zoom+white&image_size=square',
        'purchaseAdvice': '长焦性价比首选',
        'specs': {'镜片组': '16片12组', '光圈叶片': '8片(圆形)', '放大倍率': '0.21倍', '防抖': '4档'}
    },
    {
        'id': 'canon-ef-100-400-45-56-l-is',
        'brand': 'Canon', 'mount': 'EF', 'model': 'Canon EF 100-400mm f/4.5-5.6L IS USM',
        'modelCode': 'EF100-400/4.5-5.6L IS USM', 'nickname': '大白一代', 'era': 'digital', 'year': 2006,
        'type': 'zoom', 'focalLength': '100-400mm', 'aperture': 'f/4.5-5.6', 'isStabilized': True,
        'weight': 1360, 'minFocusDistance': '1.5m', 'filterSize': '77mm',
        'priceNew': 13999, 'priceUsedMin': 5000, 'priceUsedMax': 8000, 'retentionRate': 68, 'ownershipCount': 'medium',
        'pros': ['超长焦', '带防抖', '成像优秀'],
        'cons': ['重量大', '价格昂贵'],
        'commonIssues': ['镜筒进灰', '对焦马达异响'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+100-400mm+f4.5-5.6L+IS+lens+super+telephoto+white&image_size=square',
        'purchaseAdvice': '野生动物摄影首选',
        'specs': {'镜片组': '15片12组', '光圈叶片': '8片(圆形)', '放大倍率': '0.2倍', '防抖': '4档'}
    },
    {
        'id': 'sigma-35-14-art',
        'brand': 'Sigma', 'mount': 'EF', 'model': 'Sigma 35mm f/1.4 DG HSM Art',
        'modelCode': '35/1.4 DG HSM Art', 'nickname': '适马Art人文', 'era': 'digital', 'year': 2012,
        'type': 'prime', 'focalLength': '35mm', 'aperture': 'f/1.4', 'isStabilized': False,
        'weight': 665, 'minFocusDistance': '0.3m', 'filterSize': '67mm',
        'priceNew': 5499, 'priceUsedMin': 2500, 'priceUsedMax': 4000, 'retentionRate': 70, 'ownershipCount': 'high',
        'pros': ['大光圈', '成像锐利', '人文焦段'],
        'cons': ['无防抖', '重量较大'],
        'commonIssues': ['对焦偶发不准'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Sigma+35mm+f1.4+Art+lens+wide+angle+fast+prime&image_size=square',
        'purchaseAdvice': '人文摄影首选',
        'specs': {'镜片组': '13片9组', '光圈叶片': '9片(圆形)', '放大倍率': '0.12倍'}
    },
    {
        'id': 'sigma-50-14-art',
        'brand': 'Sigma', 'mount': 'EF', 'model': 'Sigma 50mm f/1.4 DG HSM Art',
        'modelCode': '50/1.4 DG HSM Art', 'nickname': '适马Art标准', 'era': 'digital', 'year': 2014,
        'type': 'prime', 'focalLength': '50mm', 'aperture': 'f/1.4', 'isStabilized': False,
        'weight': 815, 'minFocusDistance': '0.4m', 'filterSize': '77mm',
        'priceNew': 5999, 'priceUsedMin': 2500, 'priceUsedMax': 4000, 'retentionRate': 72, 'ownershipCount': 'high',
        'pros': ['大光圈', '成像锐利', '焦外柔美'],
        'cons': ['重量大', '无防抖'],
        'commonIssues': ['对焦慢'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Sigma+50mm+f1.4+Art+lens+standard+fast+prime&image_size=square',
        'purchaseAdvice': '标准定焦首选',
        'specs': {'镜片组': '13片9组', '光圈叶片': '9片(圆形)', '放大倍率': '0.14倍'}
    },
    {
        'id': 'sigma-85-14-art',
        'brand': 'Sigma', 'mount': 'EF', 'model': 'Sigma 85mm f/1.4 DG HSM Art',
        'modelCode': '85/1.4 DG HSM Art', 'nickname': '适马Art人像', 'era': 'digital', 'year': 2017,
        'type': 'prime', 'focalLength': '85mm', 'aperture': 'f/1.4', 'isStabilized': False,
        'weight': 1160, 'minFocusDistance': '0.85m', 'filterSize': '86mm',
        'priceNew': 6999, 'priceUsedMin': 4000, 'priceUsedMax': 5500, 'retentionRate': 75, 'ownershipCount': 'high',
        'pros': ['大光圈', '成像锐利', '焦外柔美'],
        'cons': ['重量大', '无防抖'],
        'commonIssues': ['对焦慢'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Sigma+85mm+f1.4+Art+lens+portrait+fast+prime&image_size=square',
        'purchaseAdvice': '人像定焦首选',
        'specs': {'镜片组': '14片11组', '光圈叶片': '9片(圆形)', '放大倍率': '0.12倍'}
    },
    {
        'id': 'tamron-17-50-28-di',
        'brand': 'Tamron', 'mount': 'EF', 'model': 'Tamron SP 17-50mm f/2.8 Di II VC',
        'modelCode': 'SP 17-50/2.8 Di II VC (B005)', 'nickname': '腾龙1750', 'era': 'digital', 'year': 2009,
        'type': 'zoom', 'focalLength': '17-50mm', 'aperture': 'f/2.8', 'isStabilized': True,
        'weight': 550, 'minFocusDistance': '0.27m', 'filterSize': '72mm',
        'priceNew': 3999, 'priceUsedMin': 800, 'priceUsedMax': 1500, 'retentionRate': 45, 'ownershipCount': 'high',
        'pros': ['恒定f/2.8', '带防抖', '性价比高', 'APS-C专用'],
        'cons': ['APS-C专用', '边缘画质一般'],
        'commonIssues': ['对焦马达异响'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Tamron+17-50mm+f2.8+Di+II+lens+APS-C+zoom&image_size=square',
        'purchaseAdvice': 'APS-C标变首选',
        'specs': {'镜片组': '14片11组', '光圈叶片': '7片(圆形)', '放大倍率': '0.2倍', '防抖': '3档'}
    },
    {
        'id': 'tamron-18-200-35-63-di',
        'brand': 'Tamron', 'mount': 'EF', 'model': 'Tamron 18-200mm f/3.5-6.3 Di II VC',
        'modelCode': '18-200/3.5-6.3 Di II VC (B018)', 'nickname': '腾龙天涯镜', 'era': 'digital', 'year': 2014,
        'type': 'zoom', 'focalLength': '18-200mm', 'aperture': 'f/3.5-6.3', 'isStabilized': True,
        'weight': 460, 'minFocusDistance': '0.45m', 'filterSize': '62mm',
        'priceNew': 2999, 'priceUsedMin': 600, 'priceUsedMax': 1200, 'retentionRate': 38, 'ownershipCount': 'high',
        'pros': ['焦段覆盖广', '轻便', '带防抖', '性价比高'],
        'cons': ['APS-C专用', '光圈小', '长焦端画质一般'],
        'commonIssues': ['镜筒进灰'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Tamron+18-200mm+f3.5-6.3+Di+II+lens+superzoom+APS-C+B018&image_size=square',
        'purchaseAdvice': 'APS-C一镜走天下首选',
        'specs': {'镜片组': '15片11组', '光圈叶片': '7片', '放大倍率': '0.27倍', '防抖': '3档'}
    },
    # 更多RF卡口镜头
    {
        'id': 'canon-rf-50-18-stm',
        'brand': 'Canon', 'mount': 'RF', 'model': 'Canon RF 50mm f/1.8 STM',
        'modelCode': 'RF50/1.8 STM', 'nickname': 'RF小痰盂', 'era': 'mirrorless', 'year': 2019,
        'type': 'prime', 'focalLength': '50mm', 'aperture': 'f/1.8', 'isStabilized': False,
        'weight': 160, 'minFocusDistance': '0.35m', 'filterSize': '43mm',
        'priceNew': 1299, 'priceUsedMin': 600, 'priceUsedMax': 1000, 'retentionRate': 58, 'ownershipCount': 'high',
        'pros': ['超轻便', '价格便宜', 'RF原生', 'STM安静'],
        'cons': ['无防抖', '光圈较小'],
        'commonIssues': ['暂无明显问题'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+RF+50mm+f1.8+STM+lens+compact+prime+mirrorless&image_size=square',
        'purchaseAdvice': 'RF口入门首选',
        'specs': {'镜片组': '6片5组', '光圈叶片': '7片(圆形)', '放大倍率': '0.15倍'}
    },
    {
        'id': 'canon-rf-35-18-is',
        'brand': 'Canon', 'mount': 'RF', 'model': 'Canon RF 35mm f/1.8 Macro IS STM',
        'modelCode': 'RF35/1.8 Macro IS STM', 'nickname': 'RF人文微距', 'era': 'mirrorless', 'year': 2019,
        'type': 'prime', 'focalLength': '35mm', 'aperture': 'f/1.8', 'isStabilized': True,
        'weight': 265, 'minFocusDistance': '0.17m', 'filterSize': '52mm',
        'priceNew': 2499, 'priceUsedMin': 1500, 'priceUsedMax': 2000, 'retentionRate': 70, 'ownershipCount': 'high',
        'pros': ['带防抖', '微距功能', '轻便', 'RF原生'],
        'cons': ['光圈较小'],
        'commonIssues': ['暂无明显问题'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+RF+35mm+f1.8+Macro+IS+lens+wide+angle+macro+mirrorless&image_size=square',
        'purchaseAdvice': 'RF口人文首选',
        'specs': {'镜片组': '10片8组', '光圈叶片': '7片(圆形)', '放大倍率': '0.5倍', '防抖': '4档'}
    },
    {
        'id': 'canon-rf-85-2-macro',
        'brand': 'Canon', 'mount': 'RF', 'model': 'Canon RF 85mm f/2 Macro IS STM',
        'modelCode': 'RF85/2 Macro IS STM', 'nickname': 'RF人像微距', 'era': 'mirrorless', 'year': 2020,
        'type': 'prime', 'focalLength': '85mm', 'aperture': 'f/2', 'isStabilized': True,
        'weight': 500, 'minFocusDistance': '0.35m', 'filterSize': '67mm',
        'priceNew': 4999, 'priceUsedMin': 3000, 'priceUsedMax': 4000, 'retentionRate': 78, 'ownershipCount': 'high',
        'pros': ['带防抖', '微距功能', '轻便', 'RF原生'],
        'cons': ['光圈较小'],
        'commonIssues': ['暂无明显问题'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+RF+85mm+f2+Macro+IS+lens+portrait+macro+mirrorless&image_size=square',
        'purchaseAdvice': 'RF口人像首选',
        'specs': {'镜片组': '12片9组', '光圈叶片': '9片(圆形)', '放大倍率': '0.5倍', '防抖': '5档'}
    },
    {
        'id': 'canon-rf-24-105-4l-is',
        'brand': 'Canon', 'mount': 'RF', 'model': 'Canon RF 24-105mm f/4L IS USM',
        'modelCode': 'RF24-105/4L IS USM', 'nickname': 'RF小三元标变', 'era': 'mirrorless', 'year': 2018,
        'type': 'zoom', 'focalLength': '24-105mm', 'aperture': 'f/4', 'isStabilized': True,
        'weight': 690, 'minFocusDistance': '0.45m', 'filterSize': '77mm',
        'priceNew': 8999, 'priceUsedMin': 5000, 'priceUsedMax': 7000, 'retentionRate': 82, 'ownershipCount': 'high',
        'pros': ['L头品质', '带防抖', '焦段实用', 'RF原生'],
        'cons': ['光圈较小'],
        'commonIssues': ['暂无明显问题'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+RF+24-105mm+f4L+IS+lens+standard+zoom+mirrorless&image_size=square',
        'purchaseAdvice': 'RF口旅游首选',
        'specs': {'镜片组': '15片12组', '光圈叶片': '9片(圆形)', '放大倍率': '0.24倍', '防抖': '4档'}
    },
    {
        'id': 'canon-rf-70-200-4l-is',
        'brand': 'Canon', 'mount': 'RF', 'model': 'Canon RF 70-200mm f/4L IS USM',
        'modelCode': 'RF70-200/4L IS USM', 'nickname': 'RF小小白', 'era': 'mirrorless', 'year': 2020,
        'type': 'zoom', 'focalLength': '70-200mm', 'aperture': 'f/4', 'isStabilized': True,
        'weight': 695, 'minFocusDistance': '1.0m', 'filterSize': '67mm',
        'priceNew': 11999, 'priceUsedMin': 7000, 'priceUsedMax': 9000, 'retentionRate': 85, 'ownershipCount': 'high',
        'pros': ['超轻便', '带防抖', '成像优秀', 'RF原生'],
        'cons': ['光圈较小'],
        'commonIssues': ['暂无明显问题'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+RF+70-200mm+f4L+IS+lens+telephoto+zoom+lightweight+mirrorless&image_size=square',
        'purchaseAdvice': 'RF口长焦性价比首选',
        'specs': {'镜片组': '16片12组', '光圈叶片': '9片(圆形)', '放大倍率': '0.26倍', '防抖': '5档'}
    },
    {
        'id': 'canon-rf-100-400-56-8-is',
        'brand': 'Canon', 'mount': 'RF', 'model': 'Canon RF 100-400mm f/5.6-8 IS USM',
        'modelCode': 'RF100-400/5.6-8 IS USM', 'nickname': 'RF便携长焦', 'era': 'mirrorless', 'year': 2021,
        'type': 'zoom', 'focalLength': '100-400mm', 'aperture': 'f/5.6-8', 'isStabilized': True,
        'weight': 710, 'minFocusDistance': '0.9m', 'filterSize': '67mm',
        'priceNew': 7499, 'priceUsedMin': 4500, 'priceUsedMax': 6000, 'retentionRate': 80, 'ownershipCount': 'high',
        'pros': ['超轻便', '带防抖', '焦段实用', 'RF原生'],
        'cons': ['光圈较小'],
        'commonIssues': ['暂无明显问题'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+RF+100-400mm+f5.6-8+IS+lens+telephoto+zoom+compact+mirrorless&image_size=square',
        'purchaseAdvice': 'RF口长焦入门首选',
        'specs': {'镜片组': '17片13组', '光圈叶片': '9片(圆形)', '放大倍率': '0.4倍', '防抖': '5档'}
    },
    {
        'id': 'canon-rf-800-11-is',
        'brand': 'Canon', 'mount': 'RF', 'model': 'Canon RF 800mm f/11 IS STM',
        'modelCode': 'RF800/11 IS STM', 'nickname': 'RF便携大炮', 'era': 'mirrorless', 'year': 2021,
        'type': 'prime', 'focalLength': '800mm', 'aperture': 'f/11', 'isStabilized': True,
        'weight': 1260, 'minFocusDistance': '4.5m', 'filterSize': '内置',
        'priceNew': 8999, 'priceUsedMin': 5000, 'priceUsedMax': 7000, 'retentionRate': 75, 'ownershipCount': 'medium',
        'pros': ['超轻便超长焦', '带防抖', 'RF原生'],
        'cons': ['光圈固定f/11', '对焦慢'],
        'commonIssues': ['暂无明显问题'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+RF+800mm+f11+IS+lens+super+telephoto+compact+mirrorless&image_size=square',
        'purchaseAdvice': 'RF口超长焦入门首选',
        'specs': {'镜片组': '13片11组', '光圈叶片': '10片(圆形)', '放大倍率': '0.12倍', '防抖': '5档'}
    },
    # 更多APS-C镜头
    {
        'id': 'canon-ef-s-10-22-35-45-usm',
        'brand': 'Canon', 'mount': 'EF', 'model': 'Canon EF-S 10-22mm f/3.5-4.5 USM',
        'modelCode': 'EF-S10-22/3.5-4.5 USM', 'nickname': 'APS-C超广', 'era': 'digital', 'year': 2004,
        'type': 'zoom', 'focalLength': '10-22mm', 'aperture': 'f/3.5-4.5', 'isStabilized': False,
        'weight': 385, 'minFocusDistance': '0.24m', 'filterSize': '77mm',
        'priceNew': 4499, 'priceUsedMin': 1500, 'priceUsedMax': 2500, 'retentionRate': 48, 'ownershipCount': 'medium',
        'pros': ['APS-C超广角', '成像不错', 'USM对焦'],
        'cons': ['APS-C专用', '无防抖'],
        'commonIssues': ['镜筒松动'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+EF-S+10-22mm+USM+lens+ultrawide+APS-C&image_size=square',
        'purchaseAdvice': 'APS-C风光首选',
        'specs': {'镜片组': '13片10组', '光圈叶片': '6片', '放大倍率': '0.15倍'}
    },
    {
        'id': 'canon-ef-s-55-250-45-56-is',
        'brand': 'Canon', 'mount': 'EF', 'model': 'Canon EF-S 55-250mm f/4-5.6 IS',
        'modelCode': 'EF-S55-250/4-5.6 IS', 'nickname': 'APS-C长焦', 'era': 'digital', 'year': 2007,
        'type': 'zoom', 'focalLength': '55-250mm', 'aperture': 'f/4-5.6', 'isStabilized': True,
        'weight': 390, 'minFocusDistance': '1.1m', 'filterSize': '58mm',
        'priceNew': 2499, 'priceUsedMin': 500, 'priceUsedMax': 1000, 'retentionRate': 38, 'ownershipCount': 'high',
        'pros': ['轻便', '带防抖', '价格适中'],
        'cons': ['APS-C专用', '光圈小'],
        'commonIssues': ['对焦偶发不准'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+EF-S+55-250mm+IS+lens+telephoto+APS-C&image_size=square',
        'purchaseAdvice': 'APS-C长焦首选',
        'specs': {'镜片组': '12片9组', '光圈叶片': '6片', '放大倍率': '0.29倍', '防抖': '3档'}
    },
    {
        'id': 'sigma-18-35-18-art',
        'brand': 'Sigma', 'mount': 'EF', 'model': 'Sigma 18-35mm f/1.8 DC HSM Art',
        'modelCode': '18-35/1.8 DC HSM Art', 'nickname': '适马Art超广', 'era': 'digital', 'year': 2013,
        'type': 'zoom', 'focalLength': '18-35mm', 'aperture': 'f/1.8', 'isStabilized': False,
        'weight': 810, 'minFocusDistance': '0.28m', 'filterSize': '72mm',
        'priceNew': 4999, 'priceUsedMin': 2500, 'priceUsedMax': 4000, 'retentionRate': 68, 'ownershipCount': 'medium',
        'pros': ['恒定f/1.8', '成像锐利', 'APS-C专用'],
        'cons': ['APS-C专用', '重量大', '无防抖'],
        'commonIssues': ['对焦马达异响'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Sigma+18-35mm+f1.8+Art+lens+wide+angle+fast+APS-C&image_size=square',
        'purchaseAdvice': 'APS-C视频首选',
        'specs': {'镜片组': '17片12组', '光圈叶片': '9片(圆形)', '放大倍率': '0.2倍'}
    },
    {
        'id': 'sigma-50-150-28-ex',
        'brand': 'Sigma', 'mount': 'EF', 'model': 'Sigma 50-150mm f/2.8 EX DC OS HSM',
        'modelCode': '50-150/2.8 EX DC OS HSM (A001)', 'nickname': '适马APS-C长焦', 'era': 'digital', 'year': 2008,
        'type': 'zoom', 'focalLength': '50-150mm', 'aperture': 'f/2.8', 'isStabilized': True,
        'weight': 890, 'minFocusDistance': '1.0m', 'filterSize': '72mm',
        'priceNew': 4999, 'priceUsedMin': 1500, 'priceUsedMax': 2500, 'retentionRate': 45, 'ownershipCount': 'medium',
        'pros': ['恒定f/2.8', '带防抖', 'APS-C专用'],
        'cons': ['APS-C专用', '重量大'],
        'commonIssues': ['防抖机构故障'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Sigma+50-150mm+f2.8+EX+lens+telephoto+APS-C&image_size=square',
        'purchaseAdvice': 'APS-C长焦首选',
        'specs': {'镜片组': '16片12组', '光圈叶片': '9片(圆形)', '放大倍率': '0.18倍', '防抖': '3档'}
    },
    {
        'id': 'tamron-10-24-35-45-di',
        'brand': 'Tamron', 'mount': 'EF', 'model': 'Tamron SP 10-24mm f/3.5-4.5 Di II',
        'modelCode': 'SP 10-24/3.5-4.5 Di II (B001)', 'nickname': '腾龙APS-C超广', 'era': 'digital', 'year': 2008,
        'type': 'zoom', 'focalLength': '10-24mm', 'aperture': 'f/3.5-4.5', 'isStabilized': False,
        'weight': 405, 'minFocusDistance': '0.2m', 'filterSize': '77mm',
        'priceNew': 3499, 'priceUsedMin': 800, 'priceUsedMax': 1500, 'retentionRate': 42, 'ownershipCount': 'medium',
        'pros': ['APS-C超广角', '轻便', '价格适中'],
        'cons': ['APS-C专用', '无防抖'],
        'commonIssues': ['镜筒松动'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Tamron+10-24mm+f3.5-4.5+Di+II+lens+ultrawide+APS-C+B001&image_size=square',
        'purchaseAdvice': 'APS-C风光入门首选',
        'specs': {'镜片组': '12片9组', '光圈叶片': '7片', '放大倍率': '0.15倍'}
    },
    {
        'id': 'tamron-16-300-35-63-di',
        'brand': 'Tamron', 'mount': 'EF', 'model': 'Tamron 16-300mm f/3.5-6.3 Di II VC PZD',
        'modelCode': '16-300/3.5-6.3 Di II VC PZD (B016)', 'nickname': '腾龙超级天涯', 'era': 'digital', 'year': 2014,
        'type': 'zoom', 'focalLength': '16-300mm', 'aperture': 'f/3.5-6.3', 'isStabilized': True,
        'weight': 545, 'minFocusDistance': '0.3m', 'filterSize': '67mm',
        'priceNew': 3999, 'priceUsedMin': 1000, 'priceUsedMax': 2000, 'retentionRate': 40, 'ownershipCount': 'medium',
        'pros': ['焦段覆盖极广', '带防抖', '轻便'],
        'cons': ['APS-C专用', '光圈小', '画质一般'],
        'commonIssues': ['镜筒进灰'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Tamron+16-300mm+f3.5-6.3+Di+II+lens+superzoom+APS-C+B016&image_size=square',
        'purchaseAdvice': 'APS-C一镜走天下首选',
        'specs': {'镜片组': '16片13组', '光圈叶片': '7片(圆形)', '放大倍率': '0.38倍', '防抖': '3档'}
    }
]

lenses.extend(additional_lenses)

with open('/workspace/src/data/lenses.json', 'w', encoding='utf-8') as f:
    json.dump(lenses, f, ensure_ascii=False, indent=2)

print(f"Added {len(additional_lenses)} lenses. Total: {len(lenses)} lenses")
