import json

with open('/workspace/src/data/lenses.json', 'r', encoding='utf-8') as f:
    lenses = json.load(f)

existing_ids = {l['id'] for l in lenses}

new_sigma_lenses = [
    # Art系列
    {
        'id': 'sigma-14-18-dg-hsm-art',
        'brand': 'Sigma',
        'mount': 'EF',
        'model': 'Sigma 14mm F1.8 DG HSM Art',
        'modelCode': '14mm F1.8 DG HSM Art',
        'nickname': '适马星空王',
        'era': 'digital',
        'year': 2017,
        'type': 'prime',
        'focalLength': '14mm',
        'aperture': 'f/1.8',
        'isStabilized': False,
        'weight': 1170,
        'minFocusDistance': '0.25m',
        'filterSize': '后置插片',
        'priceNew': 9999,
        'priceUsedMin': 4000,
        'priceUsedMax': 7000,
        'retentionRate': 65,
        'ownershipCount': 'medium',
        'pros': ['超大光圈广角', '星空利器', 'Art系列画质', '色散控制好'],
        'cons': ['重量较大', '非灯泡设计', '价格不低'],
        'commonIssues': ['镜筒进灰'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Sigma+14mm+f1.8+DG+HSM+Art+lens+wide+angle+star+astrophotography&image_size=square',
        'purchaseAdvice': '星空摄影首选广角定焦',
        'specs': {'镜片组': '11片9组', '光圈叶片': '9片(圆形)', '放大倍率': '0.15倍'}
    },
    {
        'id': 'sigma-24-14-dg-hsm-art',
        'brand': 'Sigma',
        'mount': 'EF',
        'model': 'Sigma 24mm F1.4 DG HSM Art',
        'modelCode': '24mm F1.4 DG HSM Art',
        'nickname': '适马人文王',
        'era': 'digital',
        'year': 2015,
        'type': 'prime',
        'focalLength': '24mm',
        'aperture': 'f/1.4',
        'isStabilized': False,
        'weight': 665,
        'minFocusDistance': '0.25m',
        'filterSize': '77mm',
        'priceNew': 6999,
        'priceUsedMin': 3000,
        'priceUsedMax': 5000,
        'retentionRate': 62,
        'ownershipCount': 'medium',
        'pros': ['大光圈广角', '画质优秀', '人文焦段', '做工精良'],
        'cons': ['重量略大', '近摄一般'],
        'commonIssues': ['对焦马达异响'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Sigma+24mm+f1.4+DG+HSM+Art+lens+wide+angle+street+photography&image_size=square',
        'purchaseAdvice': '人文摄影性价比之选',
        'specs': {'镜片组': '12片10组', '光圈叶片': '9片(圆形)', '放大倍率': '0.17倍'}
    },
    {
        'id': 'sigma-40-14-dg-hsm-art',
        'brand': 'Sigma',
        'mount': 'EF',
        'model': 'Sigma 40mm F1.4 DG HSM Art',
        'modelCode': '40mm F1.4 DG HSM Art',
        'nickname': '适马扫街王',
        'era': 'digital',
        'year': 2018,
        'type': 'prime',
        'focalLength': '40mm',
        'aperture': 'f/1.4',
        'isStabilized': False,
        'weight': 1260,
        'minFocusDistance': '0.4m',
        'filterSize': '82mm',
        'priceNew': 8999,
        'priceUsedMin': 4500,
        'priceUsedMax': 7500,
        'retentionRate': 68,
        'ownershipCount': 'medium',
        'pros': ['电影镜头设计', '画质顶级', '焦外美丽', '做工极致'],
        'cons': ['非常重', '价格高'],
        'commonIssues': ['暂无明显问题'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Sigma+40mm+f1.4+DG+HSM+Art+lens+cinema+quality+standard&image_size=square',
        'purchaseAdvice': '追求极致画质的专业之选',
        'specs': {'镜片组': '12片9组', '光圈叶片': '9片(圆形)', '放大倍率': '0.1倍'}
    },
    {
        'id': 'sigma-135-18-dg-hsm-art',
        'brand': 'Sigma',
        'mount': 'EF',
        'model': 'Sigma 135mm F1.8 DG HSM Art',
        'modelCode': '135mm F1.8 DG HSM Art',
        'nickname': '适马人像王',
        'era': 'digital',
        'year': 2017,
        'type': 'prime',
        'focalLength': '135mm',
        'aperture': 'f/1.8',
        'isStabilized': False,
        'weight': 1130,
        'minFocusDistance': '0.8m',
        'filterSize': '82mm',
        'priceNew': 7999,
        'priceUsedMin': 3500,
        'priceUsedMax': 6000,
        'retentionRate': 66,
        'ownershipCount': 'medium',
        'pros': ['画质惊人', '焦外梦幻', '人像利器', '性价比高'],
        'cons': ['重量大', '价格不低'],
        'commonIssues': ['暂无明显问题'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Sigma+135mm+f1.8+DG+HSM+Art+lens+portrait+bokeh+master&image_size=square',
        'purchaseAdvice': '人像摄影师必备神器',
        'specs': {'镜片组': '13片10组', '光圈叶片': '9片(圆形)', '放大倍率': '0.2倍'}
    },
    # Sports系列
    {
        'id': 'sigma-120-300-28-dg-os-hsm-sport',
        'brand': 'Sigma',
        'mount': 'EF',
        'model': 'Sigma 120-300mm F2.8 DG OS HSM Sport',
        'modelCode': '120-300mm F2.8 DG OS HSM Sport',
        'nickname': '适马大炮',
        'era': 'digital',
        'year': 2013,
        'type': 'zoom',
        'focalLength': '120-300mm',
        'aperture': 'f/2.8',
        'isStabilized': True,
        'weight': 2910,
        'minFocusDistance': '2.5m',
        'filterSize': '105mm',
        'priceNew': 18999,
        'priceUsedMin': 8000,
        'priceUsedMax': 14000,
        'retentionRate': 70,
        'ownershipCount': 'low',
        'pros': ['恒定大光圈', '防抖给力', '画质优秀', '做工顶级'],
        'cons': ['巨重', '价格昂贵'],
        'commonIssues': ['三脚架环故障'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Sigma+120-300mm+f2.8+DG+OS+HSM+Sport+lens+super+telephoto+professional&image_size=square',
        'purchaseAdvice': '专业体育/野生动物摄影利器',
        'specs': {'镜片组': '22片17组', '光圈叶片': '9片(圆形)', '放大倍率': '0.1倍', '防抖': '4档'}
    },
    {
        'id': 'sigma-60-600-45-63-dg-os-hsm-sport',
        'brand': 'Sigma',
        'mount': 'EF',
        'model': 'Sigma 60-600mm F4.5-6.3 DG OS HSM Sport',
        'modelCode': '60-600mm F4.5-6.3 DG OS HSM Sport',
        'nickname': '适马超级大炮',
        'era': 'mirrorless',
        'year': 2019,
        'type': 'zoom',
        'focalLength': '60-600mm',
        'aperture': 'f/4.5-6.3',
        'isStabilized': True,
        'weight': 2700,
        'minFocusDistance': '2.6m',
        'filterSize': '105mm',
        'priceNew': 15999,
        'priceUsedMin': 9000,
        'priceUsedMax': 13000,
        'retentionRate': 75,
        'ownershipCount': 'low',
        'pros': ['10倍变焦', '超长焦覆盖', '画质优秀', '防抖强'],
        'cons': ['重量巨大', '价格高'],
        'commonIssues': ['暂无明显问题'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Sigma+60-600mm+f4.5-6.3+DG+OS+HSM+Sport+lens+super+zoom+wildlife&image_size=square',
        'purchaseAdvice': '一镜走天涯的超长焦选择',
        'specs': {'镜片组': '25片19组', '光圈叶片': '9片(圆形)', '放大倍率': '0.15倍', '防抖': '4档'}
    },
    {
        'id': 'sigma-500-4-dg-os-hsm-sport',
        'brand': 'Sigma',
        'mount': 'EF',
        'model': 'Sigma 500mm F4 DG OS HSM Sport',
        'modelCode': '500mm F4 DG OS HSM Sport',
        'nickname': '适马巨炮',
        'era': 'digital',
        'year': 2013,
        'type': 'prime',
        'focalLength': '500mm',
        'aperture': 'f/4',
        'isStabilized': True,
        'weight': 3310,
        'minFocusDistance': '3.5m',
        'filterSize': '后置插片',
        'priceNew': 39999,
        'priceUsedMin': 18000,
        'priceUsedMax': 28000,
        'retentionRate': 68,
        'ownershipCount': 'low',
        'pros': ['大光圈超长焦', '画质顶级', '防抖给力', '做工极致'],
        'cons': ['巨重', '极其昂贵'],
        'commonIssues': ['脚架环磨损'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Sigma+500mm+f4+DG+OS+HSM+Sport+lens+super+telephoto+professional+wildlife&image_size=square',
        'purchaseAdvice': '专业野生动物/体育摄影的终极武器',
        'specs': {'镜片组': '14片10组', '光圈叶片': '9片(圆形)', '放大倍率': '0.12倍', '防抖': '4档'}
    },
    # Contemporary系列
    {
        'id': 'sigma-50-100-18-dc-hsm-art',
        'brand': 'Sigma',
        'mount': 'EF',
        'model': 'Sigma 50-100mm F1.8 DC HSM Art',
        'modelCode': '50-100mm F1.8 DC HSM Art',
        'nickname': '适马APS-C人像王',
        'era': 'digital',
        'year': 2016,
        'type': 'zoom',
        'focalLength': '50-100mm',
        'aperture': 'f/1.8',
        'isStabilized': False,
        'weight': 1490,
        'minFocusDistance': '0.95m',
        'filterSize': '82mm',
        'priceNew': 7999,
        'priceUsedMin': 3500,
        'priceUsedMax': 5500,
        'retentionRate': 60,
        'ownershipCount': 'medium',
        'pros': ['APS-C恒定f/1.8', '人像焦段', '画质优秀', '做工精良'],
        'cons': ['重量大', 'APS-C专用', '价格不低'],
        'commonIssues': ['对焦马达异响'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Sigma+50-100mm+f1.8+DC+HSM+Art+lens+APS-C+portrait+zoom&image_size=square',
        'purchaseAdvice': 'APS-C人像摄影师必备',
        'specs': {'镜片组': '15片11组', '光圈叶片': '9片(圆形)', '放大倍率': '0.15倍'}
    },
    {
        'id': 'sigma-100-400-5-63-dg-os-hsm-contemporary',
        'brand': 'Sigma',
        'mount': 'EF',
        'model': 'Sigma 100-400mm F5-6.3 DG OS HSM Contemporary',
        'modelCode': '100-400mm F5-6.3 DG OS HSM Contemporary',
        'nickname': '适马轻量长焦',
        'era': 'mirrorless',
        'year': 2017,
        'type': 'zoom',
        'focalLength': '100-400mm',
        'aperture': 'f/5-6.3',
        'isStabilized': True,
        'weight': 1140,
        'minFocusDistance': '1.6m',
        'filterSize': '67mm',
        'priceNew': 6999,
        'priceUsedMin': 3500,
        'priceUsedMax': 5500,
        'retentionRate': 68,
        'ownershipCount': 'medium',
        'pros': ['轻便', '4倍变焦', '防抖给力', '性价比高'],
        'cons': ['光圈较小'],
        'commonIssues': ['暂无明显问题'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Sigma+100-400mm+f5-6.3+DG+OS+HSM+Contemporary+lens+lightweight+telephoto&image_size=square',
        'purchaseAdvice': '日常打鸟/体育的轻便之选',
        'specs': {'镜片组': '21片15组', '光圈叶片': '9片(圆形)', '放大倍率': '0.25倍', '防抖': '4档'}
    },
    # 经典旧款
    {
        'id': 'sigma-20-18-ex-dg-asp',
        'brand': 'Sigma',
        'mount': 'EF',
        'model': 'Sigma 20mm F1.8 EX DG ASP',
        'modelCode': '20mm F1.8 EX DG ASP',
        'nickname': '适马老广角',
        'era': 'digital',
        'year': 2003,
        'type': 'prime',
        'focalLength': '20mm',
        'aperture': 'f/1.8',
        'isStabilized': False,
        'weight': 520,
        'minFocusDistance': '0.2m',
        'filterSize': '77mm',
        'priceNew': 4999,
        'priceUsedMin': 800,
        'priceUsedMax': 1500,
        'retentionRate': 30,
        'ownershipCount': 'medium',
        'pros': ['价格便宜', '大光圈广角', '轻便'],
        'cons': ['色散明显', '边角画质一般'],
        'commonIssues': ['对焦马达老化'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Sigma+20mm+f1.8+EX+DG+ASP+lens+vintage+wide+angle&image_size=square',
        'purchaseAdvice': '入门广角性价比之选',
        'specs': {'镜片组': '12片10组', '光圈叶片': '9片', '放大倍率': '0.15倍'}
    },
    {
        'id': 'sigma-24-18-ex-dg-asp',
        'brand': 'Sigma',
        'mount': 'EF',
        'model': 'Sigma 24mm F1.8 EX DG ASP',
        'modelCode': '24mm F1.8 EX DG ASP',
        'nickname': '适马老人文',
        'era': 'digital',
        'year': 2002,
        'type': 'prime',
        'focalLength': '24mm',
        'aperture': 'f/1.8',
        'isStabilized': False,
        'weight': 485,
        'minFocusDistance': '0.18m',
        'filterSize': '77mm',
        'priceNew': 4499,
        'priceUsedMin': 600,
        'priceUsedMax': 1200,
        'retentionRate': 28,
        'ownershipCount': 'medium',
        'pros': ['近摄给力', '大光圈', '价格亲民'],
        'cons': ['边角软', '色散明显'],
        'commonIssues': ['对焦马达老化'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Sigma+24mm+f1.8+EX+DG+ASP+lens+vintage+street+photography&image_size=square',
        'purchaseAdvice': '入门人文性价比之选',
        'specs': {'镜片组': '10片8组', '光圈叶片': '9片', '放大倍率': '0.27倍'}
    },
    {
        'id': 'sigma-70-28-dg-macro-art',
        'brand': 'Sigma',
        'mount': 'EF',
        'model': 'Sigma 70mm F2.8 DG MACRO Art',
        'modelCode': '70mm F2.8 DG MACRO Art',
        'nickname': '适马新微距',
        'era': 'mirrorless',
        'year': 2018,
        'type': 'prime',
        'focalLength': '70mm',
        'aperture': 'f/2.8',
        'isStabilized': False,
        'weight': 515,
        'minFocusDistance': '0.25m',
        'filterSize': '58mm',
        'priceNew': 4999,
        'priceUsedMin': 2500,
        'priceUsedMax': 4000,
        'retentionRate': 65,
        'ownershipCount': 'medium',
        'pros': ['1:1微距', '画质优秀', 'Art系列', '做工好'],
        'cons': ['价格不低', '无防抖'],
        'commonIssues': ['暂无明显问题'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Sigma+70mm+f2.8+DG+MACRO+Art+lens+closeup+macro+photography&image_size=square',
        'purchaseAdvice': '微距摄影好选择',
        'specs': {'镜片组': '13片10组', '光圈叶片': '9片(圆形)', '放大倍率': '1倍'}
    },
    {
        'id': 'sigma-105-28-ex-dg-os-hsm-macro',
        'brand': 'Sigma',
        'mount': 'EF',
        'model': 'Sigma 105mm F2.8 EX DG OS HSM MACRO',
        'modelCode': '105mm F2.8 EX DG OS HSM MACRO',
        'nickname': '适马老百微',
        'era': 'digital',
        'year': 2010,
        'type': 'prime',
        'focalLength': '105mm',
        'aperture': 'f/2.8',
        'isStabilized': True,
        'weight': 715,
        'minFocusDistance': '0.31m',
        'filterSize': '62mm',
        'priceNew': 4999,
        'priceUsedMin': 1500,
        'priceUsedMax': 2500,
        'retentionRate': 50,
        'ownershipCount': 'medium',
        'pros': ['1:1微距', '带防抖', '焦段实用'],
        'cons': ['画质一般', '价格不低'],
        'commonIssues': ['防抖机构异响'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Sigma+105mm+f2.8+EX+DG+OS+HSM+MACRO+lens+macro+closeup+stabilized&image_size=square',
        'purchaseAdvice': '入门微距防抖选择',
        'specs': {'镜片组': '16片12组', '光圈叶片': '9片', '放大倍率': '1倍', '防抖': '3档'}
    },
    {
        'id': 'sigma-300-28-apo-ex-dg',
        'brand': 'Sigma',
        'mount': 'EF',
        'model': 'Sigma 300mm F2.8 APO EX DG',
        'modelCode': '300mm F2.8 APO EX DG',
        'nickname': '适马老炮',
        'era': 'digital',
        'year': 2005,
        'type': 'prime',
        'focalLength': '300mm',
        'aperture': 'f/2.8',
        'isStabilized': False,
        'weight': 2580,
        'minFocusDistance': '2.5m',
        'filterSize': '后置插片',
        'priceNew': 14999,
        'priceUsedMin': 4000,
        'priceUsedMax': 7000,
        'retentionRate': 40,
        'ownershipCount': 'low',
        'pros': ['大光圈长焦', 'APO设计', '价格亲民'],
        'cons': ['无防抖', '重量大', '对焦慢'],
        'commonIssues': ['对焦马达故障'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Sigma+300mm+f2.8+APO+EX+DG+lens+vintage+telephoto+sports&image_size=square',
        'purchaseAdvice': '大光圈长焦性价比之选',
        'specs': {'镜片组': '11片9组', '光圈叶片': '9片', '放大倍率': '0.12倍'}
    },
    {
        'id': 'sigma-800-56-ex-dg',
        'brand': 'Sigma',
        'mount': 'EF',
        'model': 'Sigma 800mm F5.6 EX DG',
        'modelCode': '800mm F5.6 EX DG',
        'nickname': '适马超级巨炮',
        'era': 'digital',
        'year': 2006,
        'type': 'prime',
        'focalLength': '800mm',
        'aperture': 'f/5.6',
        'isStabilized': False,
        'weight': 5250,
        'minFocusDistance': '6m',
        'filterSize': '后置插片',
        'priceNew': 29999,
        'priceUsedMin': 8000,
        'priceUsedMax': 15000,
        'retentionRate': 45,
        'ownershipCount': 'low',
        'pros': ['超长焦距', '价格合理'],
        'cons': ['巨重', '无防抖', '使用不便'],
        'commonIssues': ['脚架环磨损'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Sigma+800mm+f5.6+EX+DG+lens+super+telephoto+wildlife+extreme&image_size=square',
        'purchaseAdvice': '极限野生动物摄影之选',
        'specs': {'镜片组': '15片11组', '光圈叶片': '9片', '放大倍率': '0.09倍'}
    }
]

filtered_new_lenses = [l for l in new_sigma_lenses if l['id'] not in existing_ids]
lenses.extend(filtered_new_lenses)

with open('/workspace/src/data/lenses.json', 'w', encoding='utf-8') as f:
    json.dump(lenses, f, ensure_ascii=False, indent=2)

print(f"已添加 {len(filtered_new_lenses)} 个新的适马镜头")
print(f"数据库总数: {len(lenses)} 个镜头")

# 统计
sigma_count = len([l for l in lenses if l['brand'] == 'Sigma'])
print(f"适马镜头总数: {sigma_count} 个")
