
import json

# 创建完整的EF/RF卡口镜头数据库（1987-2024）
lenses = [
    # ============ 胶片时代镜头 (1987-1999) ============
    {
        'id': 'canon-ef-50-10-l-usm',
        'brand': 'Canon',
        'mount': 'EF',
        'model': 'Canon EF 50mm f/1.0L USM',
        'modelCode': 'EF50/1.0L USM',
        'nickname': '终极夜之眼',
        'era': 'film',
        'year': 1989,
        'type': 'prime',
        'focalLength': '50mm',
        'aperture': 'f/1.0',
        'isStabilized': False,
        'weight': 2350,
        'minFocusDistance': '0.6m',
        'filterSize': '72mm',
        'priceNew': 8000,
        'priceUsedMin': 25000,
        'priceUsedMax': 40000,
        'retentionRate': 95,
        'ownershipCount': 'low',
        'pros': ['量产最大光圈', '传奇镜头', '收藏品', '做工顶级'],
        'cons': ['极其昂贵', '重量惊人(2350g)', '对焦慢'],
        'commonIssues': ['对焦马达故障', '保养要求高'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+EF+50mm+f1.0L+USM+legendary+lens+1989+big+aperture&image_size=square',
        'purchaseAdvice': '传奇镜头，收藏价值极高',
        'specs': {'镜片组': '11片9组', '光圈叶片': '8片', '放大倍率': '0.1倍'}
    },
    {
        'id': 'canon-ef-85-12-l-usm',
        'brand': 'Canon',
        'mount': 'EF',
        'model': 'Canon EF 85mm f/1.2L USM',
        'modelCode': 'EF85/1.2L USM',
        'nickname': '初代空气切割机',
        'era': 'film',
        'year': 1989,
        'type': 'prime',
        'focalLength': '85mm',
        'aperture': 'f/1.2',
        'isStabilized': False,
        'weight': 1050,
        'minFocusDistance': '1m',
        'filterSize': '72mm',
        'priceNew': 12999,
        'priceUsedMin': 3000,
        'priceUsedMax': 5500,
        'retentionRate': 42,
        'ownershipCount': 'medium',
        'pros': ['经典人像镜', '焦外柔美', 'L头品质'],
        'cons': ['对焦极慢', '无防抖', '重量大'],
        'commonIssues': ['对焦马达故障', '镜片镀膜老化'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+85mm+f1.2L+USM+lens+portrait+vintage+classic&image_size=square',
        'purchaseAdvice': '收藏价值大于实用，慎买',
        'specs': {'镜片组': '7片6组', '光圈叶片': '8片(圆形)', '放大倍率': '0.11倍'}
    },
    {
        'id': 'canon-ef-50-18',
        'brand': 'Canon',
        'mount': 'EF',
        'model': 'Canon EF 50mm f/1.8',
        'modelCode': 'EF50/1.8',
        'nickname': 'EF初代痰盂',
        'era': 'film',
        'year': 1987,
        'type': 'prime',
        'focalLength': '50mm',
        'aperture': 'f/1.8',
        'isStabilized': False,
        'weight': 190,
        'minFocusDistance': '0.45m',
        'filterSize': '52mm',
        'priceNew': 500,
        'priceUsedMin': 200,
        'priceUsedMax': 500,
        'retentionRate': 70,
        'ownershipCount': 'high',
        'pros': ['EF初代标头', '便宜大碗', '轻便实用'],
        'cons': ['塑料感强', '对焦马达慢'],
        'commonIssues': ['卡口容易坏', '对焦不准'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+EF+50mm+f1.8+version+1+1987+lens&image_size=square',
        'purchaseAdvice': '初代EF标头，收藏意义大于实用',
        'specs': {'镜片组': '5片5组', '光圈叶片': '5片', '放大倍率': '0.15倍'}
    },
    {
        'id': 'canon-ef-50-18-ii',
        'brand': 'Canon',
        'mount': 'EF',
        'model': 'Canon EF 50mm f/1.8 II',
        'modelCode': 'EF50/1.8 II',
        'nickname': '小痰盂二代',
        'era': 'film',
        'year': 1990,
        'type': 'prime',
        'focalLength': '50mm',
        'aperture': 'f/1.8',
        'isStabilized': False,
        'weight': 130,
        'minFocusDistance': '0.45m',
        'filterSize': '52mm',
        'priceNew': 899,
        'priceUsedMin': 100,
        'priceUsedMax': 300,
        'retentionRate': 34,
        'ownershipCount': 'high',
        'pros': ['超级便宜', '超轻便', '焦外尚可'],
        'cons': ['塑料卡口', '对焦慢', '画质一般'],
        'commonIssues': ['卡口断裂', '对焦环松动'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+50mm+f1.8+II+lens+cheap+prime+small&image_size=square',
        'purchaseAdvice': '新手入门练手首选',
        'specs': {'镜片组': '5片5组', '光圈叶片': '5片', '放大倍率': '0.15倍'}
    },
    {
        'id': 'canon-ef-35-2',
        'brand': 'Canon',
        'mount': 'EF',
        'model': 'Canon EF 35mm f/2',
        'modelCode': 'EF35/2',
        'nickname': '平民广角',
        'era': 'film',
        'year': 1990,
        'type': 'prime',
        'focalLength': '35mm',
        'aperture': 'f/2',
        'isStabilized': False,
        'weight': 215,
        'minFocusDistance': '0.3m',
        'filterSize': '52mm',
        'priceNew': 1999,
        'priceUsedMin': 300,
        'priceUsedMax': 600,
        'retentionRate': 30,
        'ownershipCount': 'high',
        'pros': ['超轻便', '价格极低', '人文视角'],
        'cons': ['无防抖', '光圈较小', '边缘画质一般'],
        'commonIssues': ['对焦环松动', '卡口磨损'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+35mm+f2+lens+wide+prime+compact+vintage&image_size=square',
        'purchaseAdvice': '性价比无敌，入门人文首选',
        'specs': {'镜片组': '5片4组', '光圈叶片': '6片', '放大倍率': '0.15倍'}
    },
    {
        'id': 'canon-ef-50-14-usm',
        'brand': 'Canon',
        'mount': 'EF',
        'model': 'Canon EF 50mm f/1.4 USM',
        'modelCode': 'EF50/1.4 USM',
        'nickname': '小痰盂升级款',
        'era': 'film',
        'year': 1993,
        'type': 'prime',
        'focalLength': '50mm',
        'aperture': 'f/1.4',
        'isStabilized': False,
        'weight': 290,
        'minFocusDistance': '0.45m',
        'filterSize': '58mm',
        'priceNew': 2899,
        'priceUsedMin': 600,
        'priceUsedMax': 1200,
        'retentionRate': 42,
        'ownershipCount': 'high',
        'pros': ['轻便小巧', '价格实惠', '焦外柔美', '经典标头'],
        'cons': ['无防抖', '对焦速度一般', '塑料卡口'],
        'commonIssues': ['对焦环松动', '光圈叶片油润'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+50mm+f1.4+USM+lens+classic+prime+vintage&image_size=square',
        'purchaseAdvice': '入门首选，性价比极高',
        'specs': {'镜片组': '7片6组', '光圈叶片': '8片(圆形)', '放大倍率': '0.15倍'}
    },
    {
        'id': 'canon-ef-85-18-usm',
        'brand': 'Canon',
        'mount': 'EF',
        'model': 'Canon EF 85mm f/1.8 USM',
        'modelCode': 'EF85/1.8 USM',
        'nickname': '人像入门镜',
        'era': 'film',
        'year': 1992,
        'type': 'prime',
        'focalLength': '85mm',
        'aperture': 'f/1.8',
        'isStabilized': False,
        'weight': 425,
        'minFocusDistance': '0.85m',
        'filterSize': '58mm',
        'priceNew': 3999,
        'priceUsedMin': 1000,
        'priceUsedMax': 2000,
        'retentionRate': 50,
        'ownershipCount': 'high',
        'pros': ['轻便', '价格适中', '人像焦外好', '对焦快速'],
        'cons': ['无防抖', '边缘画质一般', '塑料感'],
        'commonIssues': ['对焦环阻尼变涩', '镀膜老化'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+85mm+f1.8+USM+lens+portrait+affordable&image_size=square',
        'purchaseAdvice': '人像入门首选，二手超值',
        'specs': {'镜片组': '8片6组', '光圈叶片': '8片(圆形)', '放大倍率': '0.11倍'}
    },
    {
        'id': 'canon-ef-28-70-28l-usm',
        'brand': 'Canon',
        'mount': 'EF',
        'model': 'Canon EF 28-70mm f/2.8L USM',
        'modelCode': 'EF28-70/2.8L USM',
        'nickname': '老镜皇',
        'era': 'film',
        'year': 1993,
        'type': 'zoom',
        'focalLength': '28-70mm',
        'aperture': 'f/2.8',
        'isStabilized': False,
        'weight': 825,
        'minFocusDistance': '0.5m',
        'filterSize': '77mm',
        'priceNew': 12999,
        'priceUsedMin': 1500,
        'priceUsedMax': 3000,
        'retentionRate': 23,
        'ownershipCount': 'medium',
        'pros': ['经典L头', '做工扎实', '焦外柔美', '保值经典'],
        'cons': ['无防抖', '对焦较慢', '体积大', '边缘画质软'],
        'commonIssues': ['对焦马达故障', '镜筒进灰严重'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+28-70mm+f2.8L+USM+lens+classic+professional+zoom&image_size=square',
        'purchaseAdvice': '收藏价值大于实用价值',
        'specs': {'镜片组': '15片12组', '光圈叶片': '8片(圆形)', '放大倍率': '0.25倍'}
    },
    {
        'id': 'canon-ef-100-300-45-56l-usm',
        'brand': 'Canon',
        'mount': 'EF',
        'model': 'Canon EF 100-300mm f/4.5-5.6L USM',
        'modelCode': 'EF100-400/4.5-5.6L USM',
        'nickname': '老白头',
        'era': 'film',
        'year': 1995,
        'type': 'zoom',
        'focalLength': '100-300mm',
        'aperture': 'f/4.5-5.6',
        'isStabilized': False,
        'weight': 720,
        'minFocusDistance': '1.5m',
        'filterSize': '58mm',
        'priceNew': 6999,
        'priceUsedMin': 800,
        'priceUsedMax': 1500,
        'retentionRate': 21,
        'ownershipCount': 'medium',
        'pros': ['轻便长焦', 'L头品质', '价格便宜', '做工扎实'],
        'cons': ['无防抖', '光圈小', '对焦慢', '画质一般'],
        'commonIssues': ['对焦马达老化', '镜筒伸缩卡顿'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+100-300mm+f4.5-5.6L+USM+lens+telephoto+vintage&image_size=square',
        'purchaseAdvice': '适合预算有限的长焦需求',
        'specs': {'镜片组': '12片10组', '光圈叶片': '6片', '放大倍率': '0.2倍'}
    },
    {
        'id': 'canon-ef-70-200-28l-usm',
        'brand': 'Canon',
        'mount': 'EF',
        'model': 'Canon EF 70-200mm f/2.8L USM',
        'modelCode': 'EF70-200/2.8L USM',
        'nickname': '小白',
        'era': 'film',
        'year': 1995,
        'type': 'zoom',
        'focalLength': '70-200mm',
        'aperture': 'f/2.8',
        'isStabilized': False,
        'weight': 1310,
        'minFocusDistance': '1.5m',
        'filterSize': '77mm',
        'priceNew': 10999,
        'priceUsedMin': 2000,
        'priceUsedMax': 4000,
        'retentionRate': 36,
        'ownershipCount': 'medium',
        'pros': ['经典L头', '成像锐利', '做工扎实', '恒定光圈'],
        'cons': ['无防抖', '重量大', '对焦慢'],
        'commonIssues': ['对焦马达故障', '镜筒密封老化'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+70-200mm+f2.8L+USM+lens+white+telephoto+vintage&image_size=square',
        'purchaseAdvice': '收藏经典，实用不如新版',
        'specs': {'镜片组': '18片14组', '光圈叶片': '8片(圆形)', '放大倍率': '0.19倍'}
    },
    {
        'id': 'canon-ef-135-2l-usm',
        'brand': 'Canon',
        'mount': 'EF',
        'model': 'Canon EF 135mm f/2L USM',
        'modelCode': 'EF135/2L USM',
        'nickname': '美人头',
        'era': 'film',
        'year': 1996,
        'type': 'prime',
        'focalLength': '135mm',
        'aperture': 'f/2',
        'isStabilized': False,
        'weight': 750,
        'minFocusDistance': '0.9m',
        'filterSize': '72mm',
        'priceNew': 8999,
        'priceUsedMin': 3000,
        'priceUsedMax': 5000,
        'retentionRate': 56,
        'ownershipCount': 'high',
        'pros': ['人像神镜', '焦外如奶油', '轻便', '画质优秀'],
        'cons': ['无防抖', '对焦稍慢', '价格较高'],
        'commonIssues': ['对焦马达异响', '镀膜老化'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+135mm+f2L+USM+lens+portrait+prime+classic&image_size=square',
        'purchaseAdvice': '人像摄影经典，二手超值',
        'specs': {'镜片组': '8片7组', '光圈叶片': '8片(圆形)', '放大倍率': '0.15倍'}
    },
    {
        'id': 'canon-ef-200-18l-usm',
        'brand': 'Canon',
        'mount': 'EF',
        'model': 'Canon EF 200mm f/1.8L USM',
        'modelCode': 'EF200/1.8L USM',
        'nickname': '空气切割机',
        'era': 'film',
        'year': 1996,
        'type': 'prime',
        'focalLength': '200mm',
        'aperture': 'f/1.8',
        'isStabilized': False,
        'weight': 2520,
        'minFocusDistance': '1.5m',
        'filterSize': '48mm内置',
        'priceNew': 49999,
        'priceUsedMin': 25000,
        'priceUsedMax': 38000,
        'retentionRate': 76,
        'ownershipCount': 'low',
        'pros': ['超大光圈', '虚化极致', '画质顶级', '稀有珍品'],
        'cons': ['超级重(2520g)', '价格天价', '无防抖', '携带不便'],
        'commonIssues': ['对焦马达故障', '镜筒密封问题'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+200mm+f1.8L+USM+lens+super+fast+telephoto+rare&image_size=square',
        'purchaseAdvice': '土豪专属，收藏价值高',
        'specs': {'镜片组': '14片11组', '光圈叶片': '8片(圆形)', '放大倍率': '0.12倍'}
    },
    {
        'id': 'canon-ef-180-35l-macro',
        'brand': 'Canon',
        'mount': 'EF',
        'model': 'Canon EF 180mm f/3.5L Macro USM',
        'modelCode': 'EF180/3.5L Macro',
        'nickname': '长焦微距',
        'era': 'film',
        'year': 1996,
        'type': 'prime',
        'focalLength': '180mm',
        'aperture': 'f/3.5',
        'isStabilized': False,
        'weight': 1090,
        'minFocusDistance': '0.48m',
        'filterSize': '72mm',
        'priceNew': 12999,
        'priceUsedMin': 3000,
        'priceUsedMax': 5000,
        'retentionRate': 40,
        'ownershipCount': 'low',
        'pros': ['长焦微距', '1:1放大', '背景虚化好'],
        'cons': ['重量大', '无防抖', '价格高'],
        'commonIssues': ['对焦马达故障'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+180mm+f3.5L+Macro+lens+telephoto+closeup&image_size=square',
        'purchaseAdvice': '专业微距用户可选',
        'specs': {'镜片组': '14片10组', '光圈叶片': '8片(圆形)', '放大倍率': '1倍'}
    },
    {
        'id': 'canon-ef-24-85-35-45-usm',
        'brand': 'Canon',
        'mount': 'EF',
        'model': 'Canon EF 24-85mm f/3.5-4.5 USM',
        'modelCode': 'EF24-85/3.5-4.5 USM',
        'nickname': '老套头',
        'era': 'film',
        'year': 1998,
        'type': 'zoom',
        'focalLength': '24-85mm',
        'aperture': 'f/3.5-4.5',
        'isStabilized': False,
        'weight': 425,
        'minFocusDistance': '0.4m',
        'filterSize': '72mm',
        'priceNew': 3499,
        'priceUsedMin': 400,
        'priceUsedMax': 800,
        'retentionRate': 23,
        'ownershipCount': 'high',
        'pros': ['焦段实用', '轻便', '价格便宜', '全幅可用'],
        'cons': ['光圈小', '无防抖', '边缘画质差'],
        'commonIssues': ['对焦马达异响', '镜筒松动'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+24-85mm+f3.5-4.5+USM+lens+standard+zoom+old&image_size=square',
        'purchaseAdvice': '练手用，不建议长期使用',
        'specs': {'镜片组': '12片10组', '光圈叶片': '6片', '放大倍率': '0.2倍'}
    },
    {
        'id': 'canon-ef-28-200-35-56-usm',
        'brand': 'Canon',
        'mount': 'EF',
        'model': 'Canon EF 28-200mm f/3.5-5.6 USM',
        'modelCode': 'EF28-200/3.5-5.6 USM',
        'nickname': '天涯镜',
        'era': 'film',
        'year': 1998,
        'type': 'zoom',
        'focalLength': '28-200mm',
        'aperture': 'f/3.5-5.6',
        'isStabilized': False,
        'weight': 670,
        'minFocusDistance': '0.5m',
        'filterSize': '72mm',
        'priceNew': 4499,
        'priceUsedMin': 600,
        'priceUsedMax': 1200,
        'retentionRate': 27,
        'ownershipCount': 'medium',
        'pros': ['焦段覆盖广', '轻便'],
        'cons': ['光圈小', '画质差', '无防抖'],
        'commonIssues': ['对焦不准', '镜筒松动'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+28-200mm+f3.5-5.6+USM+lens+superzoom+old&image_size=square',
        'purchaseAdvice': '不推荐，画质太差',
        'specs': {'镜片组': '15片12组', '光圈叶片': '6片', '放大倍率': '0.2倍'}
    },
    {
        'id': 'canon-ef-100-28-macro',
        'brand': 'Canon',
        'mount': 'EF',
        'model': 'Canon EF 100mm f/2.8 Macro USM',
        'modelCode': 'EF100/2.8 Macro USM',
        'nickname': '百微',
        'era': 'film',
        'year': 1998,
        'type': 'prime',
        'focalLength': '100mm',
        'aperture': 'f/2.8',
        'isStabilized': False,
        'weight': 540,
        'minFocusDistance': '0.31m',
        'filterSize': '58mm',
        'priceNew': 4999,
        'priceUsedMin': 1500,
        'priceUsedMax': 2500,
        'retentionRate': 48,
        'ownershipCount': 'high',
        'pros': ['1:1微距', '成像锐利', '焦外柔美', '人像也可用'],
        'cons': ['无防抖', '对焦稍慢'],
        'commonIssues': ['对焦马达异响'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+100mm+f2.8+Macro+lens+closeup+prime&image_size=square',
        'purchaseAdvice': '微距摄影入门首选',
        'specs': {'镜片组': '12片8组', '光圈叶片': '8片(圆形)', '放大倍率': '1倍'}
    },
    {
        'id': 'canon-ef-300-4l-is-usm',
        'brand': 'Canon',
        'mount': 'EF',
        'model': 'Canon EF 300mm f/4L IS USM',
        'modelCode': 'EF300/4L IS USM',
        'nickname': '小绿',
        'era': 'film',
        'year': 1999,
        'type': 'prime',
        'focalLength': '300mm',
        'aperture': 'f/4',
        'isStabilized': True,
        'weight': 1190,
        'minFocusDistance': '1.5m',
        'filterSize': '77mm',
        'priceNew': 13999,
        'priceUsedMin': 5000,
        'priceUsedMax': 8000,
        'retentionRate': 58,
        'ownershipCount': 'medium',
        'pros': ['轻便长焦', '带防抖', '画质优秀'],
        'cons': ['价格较高', '光圈较小'],
        'commonIssues': ['脚架环松动'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+300mm+f4L+IS+lens+telephoto+green+ring&image_size=square',
        'purchaseAdvice': '鸟类摄影入门首选',
        'specs': {'镜片组': '14片10组', '光圈叶片': '8片(圆形)', '放大倍率': '0.14倍', '防抖': '3档'}
    },
    {
        'id': 'canon-ef-400-56l-usm',
        'brand': 'Canon',
        'mount': 'EF',
        'model': 'Canon EF 400mm f/5.6L USM',
        'modelCode': 'EF400/5.6L USM',
        'nickname': '小小白炮',
        'era': 'film',
        'year': 1993,
        'type': 'prime',
        'focalLength': '400mm',
        'aperture': 'f/5.6',
        'isStabilized': False,
        'weight': 1250,
        'minFocusDistance': '3.5m',
        'filterSize': '77mm',
        'priceNew': 14999,
        'priceUsedMin': 4000,
        'priceUsedMax': 7000,
        'retentionRate': 48,
        'ownershipCount': 'medium',
        'pros': ['轻便400mm', '画质优秀', 'L头品质'],
        'cons': ['无防抖', '光圈小', '对焦慢'],
        'commonIssues': ['对焦马达老化'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+400mm+f5.6L+USM+lens+super+telephoto+white&image_size=square',
        'purchaseAdvice': '预算有限的长焦选择',
        'specs': {'镜片组': '11片9组', '光圈叶片': '8片(圆形)', '放大倍率': '0.12倍'}
    },
    # ============ 数码时代镜头 (2000-2007) ============
    {
        'id': 'canon-ef-70-200-28l-is-usm',
        'brand': 'Canon',
        'mount': 'EF',
        'model': 'Canon EF 70-200mm f/2.8L IS USM',
        'modelCode': 'EF70-200/2.8L IS USM',
        'nickname': '爱死小白',
        'era': 'digital',
        'year': 2001,
        'type': 'zoom',
        'focalLength': '70-200mm',
        'aperture': 'f/2.8',
        'isStabilized': True,
        'weight': 1470,
        'minFocusDistance': '1.5m',
        'filterSize': '77mm',
        'priceNew': 14999,
        'priceUsedMin': 3500,
        'priceUsedMax': 6000,
        'retentionRate': 40,
        'ownershipCount': 'high',
        'pros': ['首款带防抖大白', '成像优秀', '防抖实用', '做工扎实'],
        'cons': ['重量大', '对焦速度一般', '防抖档位低'],
        'commonIssues': ['防抖机构故障', '镜筒进灰'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+70-200mm+f2.8L+IS+USM+lens+white+stabilized+vintage&image_size=square',
        'purchaseAdvice': '性价比高，老款依然能打',
        'specs': {'镜片组': '21片16组', '光圈叶片': '8片(圆形)', '放大倍率': '0.2倍', '防抖': '3档'}
    },
    {
        'id': 'canon-ef-16-35-28l-usm',
        'brand': 'Canon',
        'mount': 'EF',
        'model': 'Canon EF 16-35mm f/2.8L USM',
        'modelCode': 'EF16-35/2.8L USM',
        'nickname': '大三元超广一代',
        'era': 'digital',
        'year': 2001,
        'type': 'zoom',
        'focalLength': '16-35mm',
        'aperture': 'f/2.8',
        'isStabilized': False,
        'weight': 645,
        'minFocusDistance': '0.28m',
        'filterSize': '77mm',
        'priceNew': 11999,
        'priceUsedMin': 2000,
        'priceUsedMax': 4000,
        'retentionRate': 34,
        'ownershipCount': 'medium',
        'pros': ['经典超广', '星芒效果好', '对焦快速'],
        'cons': ['无防抖', '边缘画质一般', '灯泡头'],
        'commonIssues': ['前组镜片易沾污', '镜筒密闭性差'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+16-35mm+f2.8L+USM+lens+wide+angle+vintage&image_size=square',
        'purchaseAdvice': '风光入门尚可，建议升级二代',
        'specs': {'镜片组': '10片8组', '光圈叶片': '8片(圆形)', '放大倍率': '0.2倍'}
    },
    {
        'id': 'canon-ef-24-70-28l-usm',
        'brand': 'Canon',
        'mount': 'EF',
        'model': 'Canon EF 24-70mm f/2.8L USM',
        'modelCode': 'EF24-70/2.8L USM',
        'nickname': '初代镜皇',
        'era': 'digital',
        'year': 2002,
        'type': 'zoom',
        'focalLength': '24-70mm',
        'aperture': 'f/2.8',
        'isStabilized': False,
        'weight': 950,
        'minFocusDistance': '0.38m',
        'filterSize': '77mm',
        'priceNew': 11999,
        'priceUsedMin': 2500,
        'priceUsedMax': 4500,
        'retentionRate': 38,
        'ownershipCount': 'high',
        'pros': ['经典标变', '焦段实用', '成像优秀', '做工扎实'],
        'cons': ['无防抖', '边缘画质软', '容易进灰'],
        'commonIssues': ['镜筒进灰严重', '对焦马达故障'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+24-70mm+f2.8L+USM+lens+standard+zoom+classic&image_size=square',
        'purchaseAdvice': '预算有限可选，注意检查进灰',
        'specs': {'镜片组': '13片10组', '光圈叶片': '8片(圆形)', '放大倍率': '0.29倍'}
    },
    {
        'id': 'sigma-24-70-28-ex',
        'brand': 'Sigma',
        'mount': 'EF',
        'model': 'Sigma 24-70mm f/2.8 EX DG HSM',
        'modelCode': '24-70/2.8 EX DG HSM',
        'nickname': '老款2470ex',
        'era': 'digital',
        'year': 2002,
        'type': 'zoom',
        'focalLength': '24-70mm',
        'aperture': 'f/2.8',
        'isStabilized': False,
        'weight': 830,
        'minFocusDistance': '0.38m',
        'filterSize': '77mm',
        'priceNew': 5999,
        'priceUsedMin': 1000,
        'priceUsedMax': 2000,
        'retentionRate': 28,
        'ownershipCount': 'medium',
        'pros': ['价格便宜', '恒定f/2.8', '焦段实用'],
        'cons': ['边缘画质差', '对焦慢', '做工一般'],
        'commonIssues': ['对焦马达故障', '镜筒松动'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Sigma+24-70mm+f2.8+EX+lens+standard+zoom+old&image_size=square',
        'purchaseAdvice': '老款性价比尚可，不如Art版',
        'specs': {'镜片组': '13片10组', '光圈叶片': '9片(圆形)', '放大倍率': '0.28倍'}
    },
    {
        'id': 'tamron-28-75-28-xr',
        'brand': 'Tamron',
        'mount': 'EF',
        'model': 'Tamron SP 28-75mm f/2.8 XR Di LD Aspherical [IF]',
        'modelCode': 'SP 28-75/2.8 XR Di (A09)',
        'nickname': '腾龙老A09',
        'era': 'digital',
        'year': 2002,
        'type': 'zoom',
        'focalLength': '28-75mm',
        'aperture': 'f/2.8',
        'isStabilized': False,
        'weight': 510,
        'minFocusDistance': '0.33m',
        'filterSize': '67mm',
        'priceNew': 4999,
        'priceUsedMin': 800,
        'priceUsedMax': 1500,
        'retentionRate': 28,
        'ownershipCount': 'high',
        'pros': ['轻便', '恒定f/2.8', '价格便宜'],
        'cons': ['无防抖', '边缘画质差', '对焦慢'],
        'commonIssues': ['对焦马达异响', '镜筒进灰'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Tamron+28-75mm+f2.8+XR+lens+standard+zoom+vintage&image_size=square',
        'purchaseAdvice': '预算有限入门标变',
        'specs': {'镜片组': '13片10组', '光圈叶片': '9片(圆形)', '放大倍率': '0.25倍'}
    },
    {
        'id': 'tamron-70-200-28-di',
        'brand': 'Tamron',
        'mount': 'EF',
        'model': 'Tamron SP 70-200mm f/2.8 Di LD [IF] Macro',
        'modelCode': 'SP 70-200/2.8 Di (A001)',
        'nickname': '腾龙老款长焦',
        'era': 'digital',
        'year': 2003,
        'type': 'zoom',
        'focalLength': '70-200mm',
        'aperture': 'f/2.8',
        'isStabilized': False,
        'weight': 1390,
        'minFocusDistance': '1.2m',
        'filterSize': '77mm',
        'priceNew': 6999,
        'priceUsedMin': 1500,
        'priceUsedMax': 2800,
        'retentionRate': 30,
        'ownershipCount': 'medium',
        'pros': ['恒定f/2.8', '带微距', '价格适中'],
        'cons': ['无防抖', '重量大', '对焦慢'],
        'commonIssues': ['对焦马达故障', '镜筒密封差'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Tamron+70-200mm+f2.8+Di+lens+telephoto+old+model&image_size=square',
        'purchaseAdvice': '预算有限长焦选择',
        'specs': {'镜片组': '18片13组', '光圈叶片': '9片(圆形)', '放大倍率': '0.25倍'}
    },
    {
        'id': 'canon-ef-75-300-45-56-is-usm',
        'brand': 'Canon',
        'mount': 'EF',
        'model': 'Canon EF 75-300mm f/4-5.6 IS USM',
        'modelCode': 'EF75-300/4-5.6 IS USM',
        'nickname': '防抖版入门长焦',
        'era': 'digital',
        'year': 2003,
        'type': 'zoom',
        'focalLength': '75-300mm',
        'aperture': 'f/4-5.6',
        'isStabilized': True,
        'weight': 545,
        'minFocusDistance': '1.5m',
        'filterSize': '58mm',
        'priceNew': 3499,
        'priceUsedMin': 800,
        'priceUsedMax': 1500,
        'retentionRate': 40,
        'ownershipCount': 'high',
        'pros': ['带防抖', '轻便', '价格适中'],
        'cons': ['光圈小', '画质一般'],
        'commonIssues': ['防抖机构故障'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+75-300mm+f4-5.6+IS+lens+budget+telephoto+stabilized&image_size=square',
        'purchaseAdvice': '入门长焦带防抖，性价比尚可',
        'specs': {'镜片组': '12片10组', '光圈叶片': '6片', '放大倍率': '0.15倍', '防抖': '2档'}
    },
    {
        'id': 'tamron-90-28-macro',
        'brand': 'Tamron',
        'mount': 'EF',
        'model': 'Tamron SP 90mm f/2.8 Di Macro 1:1',
        'modelCode': 'SP 90/2.8 Di Macro (G005)',
        'nickname': '腾龙微距',
        'era': 'digital',
        'year': 2004,
        'type': 'prime',
        'focalLength': '90mm',
        'aperture': 'f/2.8',
        'isStabilized': False,
        'weight': 405,
        'minFocusDistance': '0.29m',
        'filterSize': '55mm',
        'priceNew': 3999,
        'priceUsedMin': 1200,
        'priceUsedMax': 2000,
        'retentionRate': 48,
        'ownershipCount': 'medium',
        'pros': ['1:1微距', '成像锐利', '轻便', '价格适中'],
        'cons': ['无防抖', '对焦慢'],
        'commonIssues': ['对焦马达异响'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Tamron+90mm+f2.8+macro+lens+prime+closeup&image_size=square',
        'purchaseAdvice': '微距入门首选',
        'specs': {'镜片组': '11片8组', '光圈叶片': '9片(圆形)', '放大倍率': '1倍'}
    },
    {
        'id': 'sigma-24-60-28-ex',
        'brand': 'Sigma',
        'mount': 'EF',
        'model': 'Sigma 24-60mm f/2.8 EX DG',
        'modelCode': '24-60/2.8 EX DG',
        'nickname': '适马标变',
        'era': 'digital',
        'year': 2004,
        'type': 'zoom',
        'focalLength': '24-60mm',
        'aperture': 'f/2.8',
        'isStabilized': False,
        'weight': 550,
        'minFocusDistance': '0.35m',
        'filterSize': '77mm',
        'priceNew': 4299,
        'priceUsedMin': 600,
        'priceUsedMax': 1200,
        'retentionRate': 28,
        'ownershipCount': 'medium',
        'pros': ['轻便', '恒定f/2.8', '价格便宜'],
        'cons': ['无防抖', '边缘画质差', '对焦慢'],
        'commonIssues': ['对焦马达故障'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Sigma+24-60mm+f2.8+EX+lens+standard+zoom+old&image_size=square',
        'purchaseAdvice': '老款性价比尚可',
        'specs': {'镜片组': '12片9组', '光圈叶片': '9片(圆形)', '放大倍率': '0.28倍'}
    },
    {
        'id': 'canon-ef-100-400-is-usm',
        'brand': 'Canon',
        'mount': 'EF',
        'model': 'Canon EF 100-400mm f/4.5-5.6L IS USM',
        'modelCode': 'EF100-400/4.5-5.6L IS USM',
        'nickname': '大白',
        'era': 'digital',
        'year': 2005,
        'type': 'zoom',
        'focalLength': '100-400mm',
        'aperture': 'f/4.5-5.6',
        'isStabilized': True,
        'weight': 1360,
        'minFocusDistance': '1.8m',
        'filterSize': '77mm',
        'priceNew': 13999,
        'priceUsedMin': 4000,
        'priceUsedMax': 7000,
        'retentionRate': 49,
        'ownershipCount': 'high',
        'pros': ['超长焦段', '防抖实用', '画质优秀', '焦段实用'],
        'cons': ['重量大', '光圈较小', '对焦速度一般'],
        'commonIssues': ['脚架环松动', '镜筒伸缩卡顿'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+100-400mm+f4.5-5.6L+IS+lens+super+telephoto+white&image_size=square',
        'purchaseAdvice': '野生动物摄影入门首选',
        'specs': {'镜片组': '17片13组', '光圈叶片': '8片(圆形)', '放大倍率': '0.2倍', '防抖': '3档'}
    },
    {
        'id': 'canon-ef-s-17-55-28-is',
        'brand': 'Canon',
        'mount': 'EF',
        'model': 'Canon EF-S 17-55mm f/2.8 IS USM',
        'modelCode': 'EF-S17-55/2.8 IS USM',
        'nickname': 'APS-C镜皇',
        'era': 'digital',
        'year': 2006,
        'type': 'zoom',
        'focalLength': '17-55mm',
        'aperture': 'f/2.8',
        'isStabilized': True,
        'weight': 645,
        'minFocusDistance': '0.35m',
        'filterSize': '77mm',
        'priceNew': 8999,
        'priceUsedMin': 3000,
        'priceUsedMax': 5000,
        'retentionRate': 56,
        'ownershipCount': 'high',
        'pros': ['APS-C最强标变', '恒定f/2.8', '带防抖', '成像优秀'],
        'cons': ['APS-C专用', '价格较高'],
        'commonIssues': ['对焦马达故障', '镜筒进灰'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+EF-S+17-55mm+f2.8+IS+lens+APS-C+professional&image_size=square',
        'purchaseAdvice': 'APS-C用户必入',
        'specs': {'镜片组': '19片12组', '光圈叶片': '7片(圆形)', '放大倍率': '0.32倍', '防抖': '2.5档'}
    },
    {
        'id': 'canon-ef-s-55-250-4-56-is',
        'brand': 'Canon',
        'mount': 'EF',
        'model': 'Canon EF-S 55-250mm f/4-5.6 IS',
        'modelCode': 'EF-S55-250/4-5.6 IS',
        'nickname': '小钢炮',
        'era': 'digital',
        'year': 2007,
        'type': 'zoom',
        'focalLength': '55-250mm',
        'aperture': 'f/4-5.6',
        'isStabilized': True,
        'weight': 390,
        'minFocusDistance': '1.1m',
        'filterSize': '58mm',
        'priceNew': 2499,
        'priceUsedMin': 400,
        'priceUsedMax': 800,
        'retentionRate': 32,
        'ownershipCount': 'high',
        'pros': ['轻便', '带防抖', 'APS-C专用', '便宜'],
        'cons': ['APS-C专用', '光圈小', '画质一般'],
        'commonIssues': ['镜筒松动', '对焦不准'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+EF-S+55-250mm+f4-5.6+IS+lens+APS-C+telephoto&image_size=square',
        'purchaseAdvice': 'APS-C入门长焦首选',
        'specs': {'镜片组': '12片10组', '光圈叶片': '7片(圆形)', '放大倍率': '0.29倍', '防抖': '4档'}
    },
    # ============ 数码时代中期 (2008-2015) ============
    {
        'id': 'canon-ef-16-35-28l-ii',
        'brand': 'Canon',
        'mount': 'EF',
        'model': 'Canon EF 16-35mm f/2.8L II USM',
        'modelCode': 'EF16-35/2.8L II USM',
        'nickname': '大三元超广二代',
        'era': 'digital',
        'year': 2007,
        'type': 'zoom',
        'focalLength': '16-35mm',
        'aperture': 'f/2.8',
        'isStabilized': False,
        'weight': 685,
        'minFocusDistance': '0.28m',
        'filterSize': '82mm',
        'priceNew': 12999,
        'priceUsedMin': 3500,
        'priceUsedMax': 6000,
        'retentionRate': 47,
        'ownershipCount': 'high',
        'pros': ['边缘画质提升', '星芒效果出色', '对焦快速'],
        'cons': ['无防抖', '价格较高', '灯泡头'],
        'commonIssues': ['前组镜片易沾指纹'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+16-35mm+f2.8L+II+lens+wide+angle+professional&image_size=square',
        'purchaseAdvice': '风光摄影主力，二手值得',
        'specs': {'镜片组': '12片10组', '光圈叶片': '9片(圆形)', '放大倍率': '0.25倍'}
    },
    {
        'id': 'sigma-70-200-28-ex',
        'brand': 'Sigma',
        'mount': 'EF',
        'model': 'Sigma 70-200mm f/2.8 EX DG OS HSM',
        'modelCode': '70-200/2.8 EX DG OS HSM',
        'nickname': '适马小黑',
        'era': 'digital',
        'year': 2007,
        'type': 'zoom',
        'focalLength': '70-200mm',
        'aperture': 'f/2.8',
        'isStabilized': True,
        'weight': 1430,
        'minFocusDistance': '1.0m',
        'filterSize': '77mm',
        'priceNew': 7999,
        'priceUsedMin': 2500,
        'priceUsedMax': 4500,
        'retentionRate': 48,
        'ownershipCount': 'high',
        'pros': ['恒定f/2.8', '带防抖', '价格适中'],
        'cons': ['重量大', '对焦一般', '做工一般'],
        'commonIssues': ['防抖机构故障', '对焦马达异响'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Sigma+70-200mm+f2.8+EX+OS+lens+telephoto+zoom&image_size=square',
        'purchaseAdvice': '性价比长焦选择',
        'specs': {'镜片组': '18片13组', '光圈叶片': '9片(圆形)', '放大倍率': '0.25倍', '防抖': '4档'}
    },
    {
        'id': 'canon-ef-100-28l-is-macro',
        'brand': 'Canon',
        'mount': 'EF',
        'model': 'Canon EF 100mm f/2.8L IS Macro USM',
        'modelCode': 'EF100/2.8L IS Macro USM',
        'nickname': '新百微',
        'era': 'digital',
        'year': 2009,
        'type': 'prime',
        'focalLength': '100mm',
        'aperture': 'f/2.8',
        'isStabilized': True,
        'weight': 625,
        'minFocusDistance': '0.3m',
        'filterSize': '67mm',
        'priceNew': 7999,
        'priceUsedMin': 4000,
        'priceUsedMax': 6000,
        'retentionRate': 68,
        'ownershipCount': 'high',
        'pros': ['1:1微距', '带防抖', '成像锐利', '人像微距两用'],
        'cons': ['价格较高'],
        'commonIssues': ['防抖机构偶发故障'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+100mm+f2.8L+IS+Macro+lens+professional+closeup&image_size=square',
        'purchaseAdvice': '微距摄影首选，二手超值',
        'specs': {'镜片组': '15片12组', '光圈叶片': '9片(圆形)', '放大倍率': '1倍', '防抖': '4档'}
    },
    {
        'id': 'tamron-17-50-28-xr',
        'brand': 'Tamron',
        'mount': 'EF',
        'model': 'Tamron SP 17-50mm f/2.8 XR Di II VC',
        'modelCode': 'SP 17-50/2.8 XR Di II VC (B005)',
        'nickname': 'APS-C标变',
        'era': 'digital',
        'year': 2009,
        'type': 'zoom',
        'focalLength': '17-50mm',
        'aperture': 'f/2.8',
        'isStabilized': True,
        'weight': 570,
        'minFocusDistance': '0.29m',
        'filterSize': '72mm',
        'priceNew': 4999,
        'priceUsedMin': 1200,
        'priceUsedMax': 2200,
        'retentionRate': 48,
        'ownershipCount': 'high',
        'pros': ['APS-C专用', '恒定f/2.8', '带防抖', '性价比高'],
        'cons': ['APS-C专用', '边缘画质一般'],
        'commonIssues': ['对焦马达异响', '镜筒进灰'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Tamron+17-50mm+f2.8+XR+Di+II+VC+lens+APS-C+zoom+B005&image_size=square',
        'purchaseAdvice': 'APS-C用户性价比之选',
        'specs': {'镜片组': '19片14组', '光圈叶片': '7片(圆形)', '放大倍率': '0.25倍', '防抖': '4档'}
    },
    {
        'id': 'canon-ef-70-200-28l-is-ii',
        'brand': 'Canon',
        'mount': 'EF',
        'model': 'Canon EF 70-200mm f/2.8L IS II USM',
        'modelCode': 'EF70-200/2.8L IS II USM',
        'nickname': '爱死小白兔二代',
        'era': 'digital',
        'year': 2010,
        'type': 'zoom',
        'focalLength': '70-200mm',
        'aperture': 'f/2.8',
        'isStabilized': True,
        'weight': 1490,
        'minFocusDistance': '1.2m',
        'filterSize': '77mm',
        'priceNew': 15999,
        'priceUsedMin': 6000,
        'priceUsedMax': 9000,
        'retentionRate': 57,
        'ownershipCount': 'high',
        'pros': ['防抖升级', '成像锐利', '对焦快速', '口碑极佳'],
        'cons': ['重量依然大', '价格较高'],
        'commonIssues': ['对焦马达异响', '镜筒缩回机构磨损'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+70-200mm+f2.8L+IS+II+lens+white+telephoto+professional&image_size=square',
        'purchaseAdvice': '二手性价比之王',
        'specs': {'镜片组': '23片19组', '光圈叶片': '9片(圆形)', '放大倍率': '0.27倍', '防抖': '4档'}
    },
    {
        'id': 'sigma-50-14-ex',
        'brand': 'Sigma',
        'mount': 'EF',
        'model': 'Sigma 50mm f/1.4 EX DG HSM',
        'modelCode': '50/1.4 EX DG HSM',
        'nickname': '老款50ex',
        'era': 'digital',
        'year': 2006,
        'type': 'prime',
        'focalLength': '50mm',
        'aperture': 'f/1.4',
        'isStabilized': False,
        'weight': 580,
        'minFocusDistance': '0.45m',
        'filterSize': '77mm',
        'priceNew': 3999,
        'priceUsedMin': 800,
        'priceUsedMax': 1500,
        'retentionRate': 38,
        'ownershipCount': 'medium',
        'pros': ['价格适中', '焦外柔美', '全幅可用'],
        'cons': ['对焦慢', '紫边严重', '边角画质差'],
        'commonIssues': ['对焦马达故障', '镜片起雾'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Sigma+50mm+f1.4+EX+lens+prime+old+model&image_size=square',
        'purchaseAdvice': '预算有限可选，建议选Art版',
        'specs': {'镜片组': '8片6组', '光圈叶片': '9片(圆形)', '放大倍率': '0.15倍'}
    },
    {
        'id': 'tamron-18-200-35-63-di-ii',
        'brand': 'Tamron',
        'mount': 'EF',
        'model': 'Tamron 18-200mm f/3.5-6.3 Di II VC',
        'modelCode': '18-200/3.5-6.3 Di II VC (B018)',
        'nickname': '天涯镜B018',
        'era': 'digital',
        'year': 2011,
        'type': 'zoom',
        'focalLength': '18-200mm',
        'aperture': 'f/3.5-6.3',
        'isStabilized': True,
        'weight': 400,
        'minFocusDistance': '0.45m',
        'filterSize': '62mm',
        'priceNew': 3499,
        'priceUsedMin': 800,
        'priceUsedMax': 1500,
        'retentionRate': 42,
        'ownershipCount': 'high',
        'pros': ['一镜走天下', '轻便', '带防抖', '性价比高'],
        'cons': ['光圈小', '长焦端画质一般'],
        'commonIssues': ['镜筒进灰', '对焦马达异响'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Tamron+18-200mm+f3.5-6.3+Di+II+VC+lens+superzoom+B018&image_size=square',
        'purchaseAdvice': '入门一镜走天下首选',
        'specs': {'镜片组': '14片11组', '光圈叶片': '7片(圆形)', '放大倍率': '0.42倍', '防抖': '4档'}
    },
    {
        'id': 'canon-ef-40-28-stm',
        'brand': 'Canon',
        'mount': 'EF',
        'model': 'Canon EF 40mm f/2.8 STM',
        'modelCode': 'EF40/2.8 STM',
        'nickname': '饼干头',
        'era': 'digital',
        'year': 2012,
        'type': 'prime',
        'focalLength': '40mm',
        'aperture': 'f/2.8',
        'isStabilized': False,
        'weight': 130,
        'minFocusDistance': '0.3m',
        'filterSize': '52mm',
        'priceNew': 1199,
        'priceUsedMin': 400,
        'priceUsedMax': 700,
        'retentionRate': 58,
        'ownershipCount': 'high',
        'pros': ['超级小巧', 'STM安静', '街拍神器'],
        'cons': ['无防抖', '光圈小', '对焦一般'],
        'commonIssues': ['卡口松动'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+40mm+f2.8+STM+lens+compact+prime+pancake&image_size=square',
        'purchaseAdvice': '街拍便携首选',
        'specs': {'镜片组': '7片6组', '光圈叶片': '7片(圆形)', '放大倍率': '0.27倍'}
    },
    {
        'id': 'canon-ef-24-70-28l-ii',
        'brand': 'Canon',
        'mount': 'EF',
        'model': 'Canon EF 24-70mm f/2.8L II USM',
        'modelCode': 'EF24-70/2.8L II USM',
        'nickname': '镜皇',
        'era': 'digital',
        'year': 2012,
        'type': 'zoom',
        'focalLength': '24-70mm',
        'aperture': 'f/2.8',
        'isStabilized': False,
        'weight': 886,
        'minFocusDistance': '0.38m',
        'filterSize': '82mm',
        'priceNew': 13999,
        'priceUsedMin': 6500,
        'priceUsedMax': 9500,
        'retentionRate': 60,
        'ownershipCount': 'high',
        'pros': ['成像锐利', '焦段实用', '对焦快速', '做工优秀'],
        'cons': ['无防抖', '容易进灰', '价格昂贵', '边缘画质下降明显'],
        'commonIssues': ['镜筒内部容易进灰', '变焦环阻尼变涩', '对焦马达故障'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+24-70mm+f2.8L+II+lens+professional+standard+zoom&image_size=square',
        'purchaseAdvice': '注意检查是否有进灰，购买前仔细验货',
        'specs': {'镜片组': '18片13组', '光圈叶片': '9片(圆形)', '放大倍率': '0.29倍'}
    },
    {
        'id': 'sigma-18-35-18-art',
        'brand': 'Sigma',
        'mount': 'EF',
        'model': 'Sigma 18-35mm f/1.8 DC HSM Art',
        'modelCode': '18-35/1.8 DC HSM Art',
        'nickname': '适马超广神器',
        'era': 'digital',
        'year': 2013,
        'type': 'zoom',
        'focalLength': '18-35mm',
        'aperture': 'f/1.8',
        'isStabilized': False,
        'weight': 810,
        'minFocusDistance': '0.28m',
        'filterSize': '72mm',
        'priceNew': 5299,
        'priceUsedMin': 2500,
        'priceUsedMax': 4000,
        'retentionRate': 65,
        'ownershipCount': 'high',
        'pros': ['恒定f/1.8光圈', '锐度极高', 'APS-C专用', '性价比高'],
        'cons': ['重量大', 'APS-C专用', '无防抖'],
        'commonIssues': ['对焦马达异响', '镜筒做工一般'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Sigma+18-35mm+f1.8+Art+lens+APS-C+fast+zoom&image_size=square',
        'purchaseAdvice': 'APS-C人像/视频神器',
        'specs': {'镜片组': '17片12组', '光圈叶片': '9片(圆形)', '放大倍率': '0.2倍'}
    },
    {
        'id': 'canon-ef-s-18-55-is-stm',
        'brand': 'Canon',
        'mount': 'EF',
        'model': 'Canon EF-S 18-55mm f/3.5-5.6 IS STM',
        'modelCode': 'EF-S18-55/3.5-5.6 IS STM',
        'nickname': '狗头',
        'era': 'digital',
        'year': 2013,
        'type': 'zoom',
        'focalLength': '18-55mm',
        'aperture': 'f/3.5-5.6',
        'isStabilized': True,
        'weight': 205,
        'minFocusDistance': '0.25m',
        'filterSize': '58mm',
        'priceNew': 1299,
        'priceUsedMin': 200,
        'priceUsedMax': 400,
        'retentionRate': 31,
        'ownershipCount': 'high',
        'pros': ['极轻便', '带防抖', '价格便宜'],
        'cons': ['APS-C专用', '光圈小', '画质一般'],
        'commonIssues': ['镜筒松动', '对焦不准'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+EF-S+18-55mm+IS+STM+lens+kit+lens+entry&image_size=square',
        'purchaseAdvice': '入门套机头，练手用',
        'specs': {'镜片组': '12片9组', '光圈叶片': '6片', '放大倍率': '0.34倍', '防抖': '3档'}
    },
    {
        'id': 'sigma-18-200-35-63-dc',
        'brand': 'Sigma',
        'mount': 'EF',
        'model': 'Sigma 18-200mm f/3.5-6.3 DC OS HSM',
        'modelCode': '18-200/3.5-6.3 DC OS HSM (C014)',
        'nickname': '适马天涯镜',
        'era': 'digital',
        'year': 2013,
        'type': 'zoom',
        'focalLength': '18-200mm',
        'aperture': 'f/3.5-6.3',
        'isStabilized': True,
        'weight': 430,
        'minFocusDistance': '0.45m',
        'filterSize': '62mm',
        'priceNew': 3299,
        'priceUsedMin': 700,
        'priceUsedMax': 1300,
        'retentionRate': 40,
        'ownershipCount': 'medium',
        'pros': ['一镜走天下', '轻便', '带防抖'],
        'cons': ['光圈小', '长焦端画质一般'],
        'commonIssues': ['镜筒进灰', '对焦马达异响'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Sigma+18-200mm+f3.5-6.3+DC+OS+HSM+lens+superzoom+C014&image_size=square',
        'purchaseAdvice': '入门一镜走天下选择',
        'specs': {'镜片组': '16片13组', '光圈叶片': '7片(圆形)', '放大倍率': '0.39倍', '防抖': '4档'}
    },
    {
        'id': 'tamron-16-300-35-63-di-ii',
        'brand': 'Tamron',
        'mount': 'EF',
        'model': 'Tamron 16-300mm f/3.5-6.3 Di II VC PZD',
        'modelCode': '16-300/3.5-6.3 Di II VC PZD (B016)',
        'nickname': '超级天涯镜',
        'era': 'digital',
        'year': 2014,
        'type': 'zoom',
        'focalLength': '16-300mm',
        'aperture': 'f/3.5-6.3',
        'isStabilized': True,
        'weight': 615,
        'minFocusDistance': '0.39m',
        'filterSize': '67mm',
        'priceNew': 4999,
        'priceUsedMin': 1200,
        'priceUsedMax': 2200,
        'retentionRate': 45,
        'ownershipCount': 'medium',
        'pros': ['超大变焦比', '一镜走天下', '带防抖'],
        'cons': ['光圈小', '长焦端画质一般', '重量较大'],
        'commonIssues': ['镜筒进灰', '对焦马达异响'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Tamron+16-300mm+f3.5-6.3+Di+II+VC+PZD+lens+superzoom+B016&image_size=square',
        'purchaseAdvice': '旅游一镜走天下首选',
        'specs': {'镜片组': '16片12组', '光圈叶片': '7片(圆形)', '放大倍率': '0.3倍', '防抖': '4档'}
    },
    {
        'id': 'sigma-150-600-5-63-contemporary',
        'brand': 'Sigma',
        'mount': 'EF',
        'model': 'Sigma 150-600mm f/5-6.3 DG OS HSM Contemporary',
        'modelCode': '150-600/5-6.3 DG OS HSM Contemporary (C015)',
        'nickname': '适马大炮C版',
        'era': 'digital',
        'year': 2014,
        'type': 'zoom',
        'focalLength': '150-600mm',
        'aperture': 'f/5-6.3',
        'isStabilized': True,
        'weight': 1930,
        'minFocusDistance': '2.6m',
        'filterSize': '95mm',
        'priceNew': 9999,
        'priceUsedMin': 4500,
        'priceUsedMax': 7000,
        'retentionRate': 60,
        'ownershipCount': 'medium',
        'pros': ['超长焦', '带防抖', '成像优秀', '性价比高'],
        'cons': ['重量大', '光圈小', '价格较高'],
        'commonIssues': ['镜筒伸缩卡顿', '脚架环松动'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Sigma+150-600mm+f5-6.3+Contemporary+lens+super+telephoto+C015&image_size=square',
        'purchaseAdvice': '打鸟入门首选',
        'specs': {'镜片组': '20片14组', '光圈叶片': '9片(圆形)', '放大倍率': '0.2倍', '防抖': '4档'}
    },
    {
        'id': 'canon-ef-50-18-stm',
        'brand': 'Canon',
        'mount': 'EF',
        'model': 'Canon EF 50mm f/1.8 STM',
        'modelCode': 'EF50/1.8 STM',
        'nickname': '小痰盂三代',
        'era': 'digital',
        'year': 2015,
        'type': 'prime',
        'focalLength': '50mm',
        'aperture': 'f/1.8',
        'isStabilized': False,
        'weight': 160,
        'minFocusDistance': '0.35m',
        'filterSize': '49mm',
        'priceNew': 699,
        'priceUsedMin': 300,
        'priceUsedMax': 500,
        'retentionRate': 72,
        'ownershipCount': 'high',
        'pros': ['极便宜', '轻便', 'STM安静', '对焦快'],
        'cons': ['无防抖', '塑料感', '光圈小'],
        'commonIssues': ['卡口脆弱'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+50mm+f1.8+STM+lens+affordable+prime+modern&image_size=square',
        'purchaseAdvice': '性价比无敌，入门必入',
        'specs': {'镜片组': '6片5组', '光圈叶片': '7片(圆形)', '放大倍率': '0.21倍'}
    },
    # ============ 无反时代 (2016-2024) ============
    {
        'id': 'tamron-24-70-28-g2',
        'brand': 'Tamron',
        'mount': 'EF',
        'model': 'Tamron SP 24-70mm f/2.8 Di VC USD G2',
        'modelCode': 'SP 24-70/2.8 Di VC USD G2 (A032)',
        'nickname': 'G2标变',
        'era': 'mirrorless',
        'year': 2017,
        'type': 'zoom',
        'focalLength': '24-70mm',
        'aperture': 'f/2.8',
        'isStabilized': True,
        'weight': 825,
        'minFocusDistance': '0.38m',
        'filterSize': '82mm',
        'priceNew': 7999,
        'priceUsedMin': 3500,
        'priceUsedMax': 5500,
        'retentionRate': 58,
        'ownershipCount': 'high',
        'pros': ['恒定f/2.8', '带防抖', '对焦快速', '成像优秀'],
        'cons': ['重量较大', '价格较高'],
        'commonIssues': ['对焦马达偶发异响'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Tamron+SP+24-70mm+f2.8+Di+VC+USD+G2+lens+professional+zoom+A032&image_size=square',
        'purchaseAdvice': '性价比标变之选',
        'specs': {'镜片组': '17片12组', '光圈叶片': '9片(圆形)', '放大倍率': '0.2倍', '防抖': '5档'}
    },
    {
        'id': 'sigma-24-70-28-art',
        'brand': 'Sigma',
        'mount': 'EF',
        'model': 'Sigma 24-70mm f/2.8 DG OS HSM Art',
        'modelCode': '24-70/2.8 DG OS HSM Art (A017)',
        'nickname': '适马标变Art',
        'era': 'mirrorless',
        'year': 2017,
        'type': 'zoom',
        'focalLength': '24-70mm',
        'aperture': 'f/2.8',
        'isStabilized': True,
        'weight': 1020,
        'minFocusDistance': '0.38m',
        'filterSize': '82mm',
        'priceNew': 8999,
        'priceUsedMin': 4500,
        'priceUsedMax': 7000,
        'retentionRate': 65,
        'ownershipCount': 'high',
        'pros': ['恒定f/2.8', '带防抖', '锐度极高', '做工优秀'],
        'cons': ['重量大', '价格较高'],
        'commonIssues': ['对焦马达偶发异响', '镜筒进灰'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Sigma+24-70mm+f2.8+DG+OS+HSM+Art+lens+professional+zoom+A017&image_size=square',
        'purchaseAdvice': 'Art系列性价比之选',
        'specs': {'镜片组': '19片15组', '光圈叶片': '9片(圆形)', '放大倍率': '0.2倍', '防抖': '4档'}
    },
    {
        'id': 'canon-ef-70-200-28l-is-iii',
        'brand': 'Canon',
        'mount': 'EF',
        'model': 'Canon EF 70-200mm f/2.8L IS III USM',
        'modelCode': 'EF70-200/2.8L IS III USM',
        'nickname': '爱死小白兔',
        'era': 'mirrorless',
        'year': 2018,
        'type': 'zoom',
        'focalLength': '70-200mm',
        'aperture': 'f/2.8',
        'isStabilized': True,
        'weight': 1480,
        'minFocusDistance': '1.2m',
        'filterSize': '77mm',
        'priceNew': 12999,
        'priceUsedMin': 8000,
        'priceUsedMax': 11000,
        'retentionRate': 78,
        'ownershipCount': 'high',
        'pros': ['成像锐利', '对焦速度极快', '防抖效果出色', '做工扎实'],
        'cons': ['重量较大(1480g)', '价格较高', '没有微距功能'],
        'commonIssues': ['对焦马达偶发异响', '镜筒缩回机构磨损'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+70-200mm+f2.8L+IS+III+lens+professional+camera+lens+black+metallic+texture&image_size=square',
        'purchaseAdvice': '强烈推荐购买二手，性价比极高',
        'specs': {'镜片组': '23片19组', '光圈叶片': '9片(圆形)', '放大倍率': '0.27倍', '防抖': '3.5档'}
    },
    {
        'id': 'canon-ef-70-200-4l-is-ii',
        'brand': 'Canon',
        'mount': 'EF',
        'model': 'Canon EF 70-200mm f/4L IS II USM',
        'modelCode': 'EF70-200/4L IS II USM',
        'nickname': '小茉莉',
        'era': 'mirrorless',
        'year': 2018,
        'type': 'zoom',
        'focalLength': '70-200mm',
        'aperture': 'f/4',
        'isStabilized': True,
        'weight': 780,
        'minFocusDistance': '1.0m',
        'filterSize': '72mm',
        'priceNew': 8299,
        'priceUsedMin': 4500,
        'priceUsedMax': 6500,
        'retentionRate': 75,
        'ownershipCount': 'high',
        'pros': ['轻便(780g)', '成像优秀', '防抖效果好', '性价比高'],
        'cons': ['恒定f/4光圈', '极端边缘画质稍软'],
        'commonIssues': ['偶尔对焦拉风箱'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+70-200mm+f4L+IS+lens+compact+professional+black&image_size=square',
        'purchaseAdvice': '性价比之选，推荐二手',
        'specs': {'镜片组': '20片15组', '光圈叶片': '9片(圆形)', '放大倍率': '0.28倍', '防抖': '3.5档'}
    },
    {
        'id': 'canon-rf-24-105-4l-is',
        'brand': 'Canon',
        'mount': 'RF',
        'model': 'Canon RF 24-105mm f/4L IS USM',
        'modelCode': 'RF24-105/4L IS USM',
        'nickname': 'RF套机头',
        'era': 'mirrorless',
        'year': 2018,
        'type': 'zoom',
        'focalLength': '24-105mm',
        'aperture': 'f/4',
        'isStabilized': True,
        'weight': 685,
        'minFocusDistance': '0.35m',
        'filterSize': '77mm',
        'priceNew': 7999,
        'priceUsedMin': 5000,
        'priceUsedMax': 7000,
        'retentionRate': 82,
        'ownershipCount': 'high',
        'pros': ['轻便', '防抖出色', '焦段实用', '对焦快速'],
        'cons': ['f/4光圈', '边缘画质一般'],
        'commonIssues': ['暂无明显问题'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+RF+24-105mm+f4L+IS+lens+standard+zoom+mirrorless&image_size=square',
        'purchaseAdvice': 'R系列套机头首选',
        'specs': {'镜片组': '16片12组', '光圈叶片': '9片(圆形)', '放大倍率': '0.3倍', '防抖': '5档'}
    },
    {
        'id': 'canon-rf-35-18-macro',
        'brand': 'Canon',
        'mount': 'RF',
        'model': 'Canon RF 35mm f/1.8 Macro IS STM',
        'modelCode': 'RF35/1.8 Macro IS STM',
        'nickname': 'RF小广角微距',
        'era': 'mirrorless',
        'year': 2019,
        'type': 'prime',
        'focalLength': '35mm',
        'aperture': 'f/1.8',
        'isStabilized': True,
        'weight': 295,
        'minFocusDistance': '0.17m',
        'filterSize': '52mm',
        'priceNew': 3999,
        'priceUsedMin': 2500,
        'priceUsedMax': 3500,
        'retentionRate': 85,
        'ownershipCount': 'high',
        'pros': ['轻便', '带防抖', '1:2微距', '性价比高'],
        'cons': ['光圈较小', '边缘画质一般'],
        'commonIssues': ['暂无明显问题'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+RF+35mm+f1.8+macro+IS+lens+compact+mirrorless&image_size=square',
        'purchaseAdvice': 'RF口入门首选',
        'specs': {'镜片组': '11片9组', '光圈叶片': '7片(圆形)', '放大倍率': '0.5倍', '防抖': '5档'}
    },
    {
        'id': 'canon-rf-50-18-stm',
        'brand': 'Canon',
        'mount': 'RF',
        'model': 'Canon RF 50mm f/1.8 STM',
        'modelCode': 'RF50/1.8 STM',
        'nickname': 'RF小痰盂',
        'era': 'mirrorless',
        'year': 2020,
        'type': 'prime',
        'focalLength': '50mm',
        'aperture': 'f/1.8',
        'isStabilized': False,
        'weight': 160,
        'minFocusDistance': '0.3m',
        'filterSize': '43mm',
        'priceNew': 1299,
        'priceUsedMin': 700,
        'priceUsedMax': 1000,
        'retentionRate': 75,
        'ownershipCount': 'high',
        'pros': ['极便宜', '轻便', 'STM安静', '对焦快速'],
        'cons': ['无防抖', '塑料感'],
        'commonIssues': ['卡口脆弱'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+RF+50mm+f1.8+STM+lens+compact+prime&image_size=square',
        'purchaseAdvice': 'RF入门必买',
        'specs': {'镜片组': '7片6组', '光圈叶片': '7片(圆形)', '放大倍率': '0.25倍'}
    },
    {
        'id': 'canon-rf-85-2-macro',
        'brand': 'Canon',
        'mount': 'RF',
        'model': 'Canon RF 85mm f/2 Macro IS STM',
        'modelCode': 'RF85/2 Macro IS STM',
        'nickname': 'RF人像微距',
        'era': 'mirrorless',
        'year': 2020,
        'type': 'prime',
        'focalLength': '85mm',
        'aperture': 'f/2',
        'isStabilized': True,
        'weight': 500,
        'minFocusDistance': '0.35m',
        'filterSize': '67mm',
        'priceNew': 6999,
        'priceUsedMin': 4500,
        'priceUsedMax': 6000,
        'retentionRate': 88,
        'ownershipCount': 'high',
        'pros': ['轻便', '带防抖', '1:2微距', '性价比极高'],
        'cons': ['光圈略小', '对焦稍慢'],
        'commonIssues': ['对焦偶发不准'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+RF+85mm+f2+macro+IS+lens+portrait+mirrorless&image_size=square',
        'purchaseAdvice': 'RF口人像性价比首选',
        'specs': {'镜片组': '12片8组', '光圈叶片': '9片(圆形)', '放大倍率': '0.5倍', '防抖': '5档'}
    },
    {
        'id': 'tamron-70-180-28-di',
        'brand': 'Tamron',
        'mount': 'EF',
        'model': 'Tamron 70-180mm f/2.8 Di III VXD',
        'modelCode': '70-180/2.8 Di III VXD (A056)',
        'nickname': '腾龙小长焦',
        'era': 'mirrorless',
        'year': 2020,
        'type': 'zoom',
        'focalLength': '70-180mm',
        'aperture': 'f/2.8',
        'isStabilized': False,
        'weight': 810,
        'minFocusDistance': '0.85m',
        'filterSize': '67mm',
        'priceNew': 7999,
        'priceUsedMin': 5500,
        'priceUsedMax': 7500,
        'retentionRate': 88,
        'ownershipCount': 'high',
        'pros': ['超轻便', '对焦极快', '锐度出色', '性价比高'],
        'cons': ['无防抖', '焦段稍短'],
        'commonIssues': ['镜筒伸缩噪音'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Tamron+70-180mm+f2.8+Di+III+lens+telephoto+compact&image_size=square',
        'purchaseAdvice': 'E口性价比长焦首选',
        'specs': {'镜片组': '15片12组', '光圈叶片': '9片(圆形)', '放大倍率': '0.25倍'}
    },
    {
        'id': 'canon-rf-100-400-56-8-is',
        'brand': 'Canon',
        'mount': 'RF',
        'model': 'Canon RF 100-400mm f/5.6-8 IS USM',
        'modelCode': 'RF100-400/5.6-8 IS USM',
        'nickname': 'RF小白胖',
        'era': 'mirrorless',
        'year': 2020,
        'type': 'zoom',
        'focalLength': '100-400mm',
        'aperture': 'f/5.6-8',
        'isStabilized': True,
        'weight': 700,
        'minFocusDistance': '0.9m',
        'filterSize': '67mm',
        'priceNew': 7999,
        'priceUsedMin': 5500,
        'priceUsedMax': 7500,
        'retentionRate': 85,
        'ownershipCount': 'high',
        'pros': ['超轻便', '防抖出色', '焦段实用', '性价比高'],
        'cons': ['光圈较小', '长焦端画质一般'],
        'commonIssues': ['对焦偶发拉风箱'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+RF+100-400mm+f5.6-8+IS+lens+telephoto+lightweight&image_size=square',
        'purchaseAdvice': 'RF口轻便长焦首选',
        'specs': {'镜片组': '15片11组', '光圈叶片': '9片(圆形)', '放大倍率': '0.4倍', '防抖': '5档'}
    },
    {
        'id': 'canon-rf-70-200-4l-is',
        'brand': 'Canon',
        'mount': 'RF',
        'model': 'Canon RF 70-200mm f/4L IS USM',
        'modelCode': 'RF70-200/4L IS USM',
        'nickname': 'RF小三元长焦',
        'era': 'mirrorless',
        'year': 2022,
        'type': 'zoom',
        'focalLength': '70-200mm',
        'aperture': 'f/4',
        'isStabilized': True,
        'weight': 695,
        'minFocusDistance': '0.7m',
        'filterSize': '72mm',
        'priceNew': 10999,
        'priceUsedMin': 8000,
        'priceUsedMax': 10000,
        'retentionRate': 88,
        'ownershipCount': 'high',
        'pros': ['超轻便', '防抖出色', '对焦快速', '成像优秀'],
        'cons': ['f/4光圈', '价格较高'],
        'commonIssues': ['暂无明显问题'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Canon+RF+70-200mm+f4L+IS+lens+telephoto+compact&image_size=square',
        'purchaseAdvice': 'RF口长焦性价比首选',
        'specs': {'镜片组': '17片13组', '光圈叶片': '9片(圆形)', '放大倍率': '0.31倍', '防抖': '5档'}
    },
    {
        'id': 'tamron-50-400-45-63-di',
        'brand': 'Tamron',
        'mount': 'EF',
        'model': 'Tamron 50-400mm f/4.5-6.3 Di III VXD',
        'modelCode': '50-400/4.5-6.3 Di III VXD (A067)',
        'nickname': '腾龙超长焦',
        'era': 'mirrorless',
        'year': 2022,
        'type': 'zoom',
        'focalLength': '50-400mm',
        'aperture': 'f/4.5-6.3',
        'isStabilized': True,
        'weight': 1155,
        'minFocusDistance': '0.45m',
        'filterSize': '77mm',
        'priceNew': 10999,
        'priceUsedMin': 8000,
        'priceUsedMax': 10000,
        'retentionRate': 90,
        'ownershipCount': 'medium',
        'pros': ['焦段覆盖广', '防抖出色', '对焦快速', '带微距'],
        'cons': ['光圈较小', '长焦端画质下降'],
        'commonIssues': ['对焦偶发不准'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Tamron+50-400mm+f4.5-6.3+Di+III+lens+super+telephoto&image_size=square',
        'purchaseAdvice': '一镜走天下首选',
        'specs': {'镜片组': '17片12组', '光圈叶片': '9片(圆形)', '放大倍率': '0.32倍', '防抖': '5档'}
    },
    {
        'id': 'sigma-85-14-dg-dn',
        'brand': 'Sigma',
        'mount': 'EF',
        'model': 'Sigma 85mm f/1.4 DG DN Art',
        'modelCode': '85/1.4 DG DN Art',
        'nickname': '适马85art二代',
        'era': 'mirrorless',
        'year': 2023,
        'type': 'prime',
        'focalLength': '85mm',
        'aperture': 'f/1.4',
        'isStabilized': False,
        'weight': 725,
        'minFocusDistance': '0.8m',
        'filterSize': '77mm',
        'priceNew': 8999,
        'priceUsedMin': 6500,
        'priceUsedMax': 8500,
        'retentionRate': 92,
        'ownershipCount': 'high',
        'pros': ['轻便', '锐度极高', '对焦快速', '焦外柔美'],
        'cons': ['无防抖', '价格较高'],
        'commonIssues': ['暂无明显问题'],
        'imageUrl': 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Sigma+85mm+f1.4+DG+DN+Art+lens+portrait+mirrorless&image_size=square',
        'purchaseAdvice': 'RF/E口人像首选',
        'specs': {'镜片组': '11片8组', '光圈叶片': '9片(圆形)', '放大倍率': '0.12倍'}
    },
]

# 统计信息
from collections import Counter
film_lenses = [l for l in lenses if l['era'] == 'film']
digital_lenses = [l for l in lenses if l['era'] == 'digital']
mirrorless_lenses = [l for l in lenses if l['era'] == 'mirrorless']

print(f'总镜头数: {len(lenses)}')
print(f'胶片时代镜头 (1987-1999): {len(film_lenses)}')
print(f'数码时代镜头 (2000-2015): {len(digital_lenses)}')
print(f'无反时代镜头 (2016-2024): {len(mirrorless_lenses)}')
print()
print('品牌分布:')
brand_count = Counter(l['brand'] for l in lenses)
for brand, count in sorted(brand_count.items(), key=lambda x: -x[1]):
    print(f'  {brand}: {count}')
print()
print('年份范围:', min(l['year'] for l in lenses), '-', max(l['year'] for l in lenses))

# 保存
with open('src/data/lenses.json', 'w', encoding='utf-8') as f:
    json.dump(lenses, f, ensure_ascii=False, indent=2)
